import { ChangeDetectionStrategy, Component, forwardRef, input, model, output, signal, booleanAttribute, numberAttribute } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
@Component({selector:'orc-date-picker',standalone:true,templateUrl:'./date-picker.component.html',styleUrl:'./date-picker.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,providers:[{provide:NG_VALUE_ACCESSOR,useExisting:forwardRef(()=>DatePickerComponent),multi:true}]})
export class DatePickerComponent implements ControlValueAccessor {
  /** PrimeNG-compatible value and configuration surface. */
  readonly value=model<any>(''); readonly label=input(''); readonly min=input(''); readonly max=input(''); readonly helperText=input(''); readonly error=input(''); readonly required=input(false, { transform: booleanAttribute }); readonly disabled=input(false, { transform: booleanAttribute });
  readonly placeholder=input<string | undefined>(undefined); readonly dateFormat=input<string | undefined>(undefined); readonly selectionMode=input<'single' | 'multiple' | 'range'>('single'); readonly showIcon=input(false, { transform: booleanAttribute }); readonly showButtonBar=input(false, { transform: booleanAttribute }); readonly showClear=input(false, { transform: booleanAttribute }); readonly inline=input(false, { transform: booleanAttribute }); readonly showTime=input(false, { transform: booleanAttribute }); readonly readonlyInput=input(false, { transform: booleanAttribute }); readonly autofocus=input(false, { transform: booleanAttribute }); readonly hourFormat=input('24'); readonly numberOfMonths=input(1, { transform: numberAttribute }); readonly minDate=input<Date | null | undefined>(undefined); readonly maxDate=input<Date | null | undefined>(undefined); readonly disabledDates=input<Date[] | undefined>(undefined); readonly disabledDays=input<number[] | undefined>(undefined); readonly view=input<'date' | 'month' | 'year'>('date'); readonly ariaLabel=input<string | undefined>(undefined); readonly ariaLabelledBy=input<string | undefined>(undefined); readonly name=input<string | undefined>(undefined); readonly inputId=input<string | undefined>(undefined); readonly tabindex=input<number | undefined>(undefined); readonly panelStyleClass=input<string | undefined>(undefined); readonly dataType=input<'date' | 'string'>('string'); readonly defaultDate=input<Date | null | undefined>(undefined);
  readonly onFocus=output<Event>(); readonly onBlur=output<Event>(); readonly onClose=output<void>(); readonly onSelect=output<any>(); readonly onClear=output<void>(); readonly onInput=output<any>(); readonly onTodayClick=output<Date>(); readonly onClearClick=output<void>(); readonly onShow=output<void>();
  protected readonly cvaDisabled=signal(false);
  private onChange:(value:string)=>void=()=>{}; private onTouched:()=>void=()=>{};
  writeValue(value:any):void{this.value.set(value??'');} registerOnChange(fn:(value:any)=>void):void{this.onChange=fn;} registerOnTouched(fn:()=>void):void{this.onTouched=fn;} setDisabledState(value:boolean):void{this.cvaDisabled.set(value);}
  inputValue(): string { const value=this.value(); if (value instanceof Date) return value.toISOString().slice(0, 10); return typeof value === 'string' ? value : ''; }
  update(event:Event):void{const value=(event.target as HTMLInputElement).value;this.value.set(value);this.onChange(value);this.onInput.emit(value);this.onSelect.emit(value);}
  focus(event:Event):void{this.onFocus.emit(event);} touch(event?:Event):void{if(event)this.onBlur.emit(event);this.onTouched();}
  clear():void{this.value.set('');this.onChange('');this.onClear.emit();this.onClearClick.emit();}
  today():void{const value=new Date();this.value.set(this.dataType()==='date'?value:value.toISOString().slice(0,10));this.onChange(this.value());this.onTodayClick.emit(value);}
}
