/**
 * Shape of the generated component API reference. The data itself is
 * generated by tools/docs/generate-component-api.mjs from
 * docs/quality/inventory.json into
 * src/app/generated/component-api/<family>.generated.ts (one lazy chunk per
 * family); this model file is the hand-maintained contract.
 */
export type ComponentApiKind = 'input' | 'model' | 'output';

export interface ComponentApiEntry {
  readonly kind: ComponentApiKind;
  readonly name: string;
  readonly type: string | null;
  readonly defaultValue: string | null;
  readonly required: boolean;
  readonly description?: string;
}

export interface ComponentApiMember {
  readonly component: string;
  readonly selector: string | null;
  readonly entries: readonly ComponentApiEntry[];
}

/** Loads one family's API reference from its generated lazy chunk. */
export type ComponentApiLoader = () => Promise<readonly ComponentApiMember[]>;
