// AUTO-GENERATED by tools/quality/generate-alias-parity.mjs — do not edit.
// Total alias guarantee: every alias entry point resolves to the same class
// (reference identity, not name equality) as its canonical declaration, and
// every import used below compiles in the spec build. Regenerate with:
//   npm run generate:alias-parity
// Alias entry points: 119. Value exports asserted: 150. Type exports resolved: 43.
import { AnimateOnScrollDirective as animate_on_scroll__AnimateOnScrollDirective } from '@ciag/orchestra/animate-on-scroll';
import { AnimateOnScrollDirective as canonical__p2_p2_utility_more__AnimateOnScrollDirective } from './p2/p2-utility-more';
import { AnimateOnScrollDirective as animateonscroll__AnimateOnScrollDirective } from '@ciag/orchestra/animateonscroll';
import { AspectRatioComponent as aspect_ratio__AspectRatioComponent } from '@ciag/orchestra/aspect-ratio';
import { AspectRatioComponent as canonical__p2_p2_layout_components__AspectRatioComponent } from './p2/p2-layout-components';
import { AutoFocusDirective as autofocus__AutoFocusDirective } from '@ciag/orchestra/autofocus';
import { AutoFocusDirective as canonical__p2_p2_input_more__AutoFocusDirective } from './p2/p2-input-more';
import { AvatarGroupComponent as avatar_group__AvatarGroupComponent } from '@ciag/orchestra/avatar-group';
import { AvatarGroupComponent as canonical__avatar_avatar_group_component__AvatarGroupComponent } from './avatar/avatar-group.component';
import { AvatarGroupComponent as avatargroup__AvatarGroupComponent } from '@ciag/orchestra/avatargroup';
import { BlockUiComponent as block_ui__BlockUiComponent } from '@ciag/orchestra/block-ui';
import { BlockUiComponent as canonical__p2_p2_block_ui_component__BlockUiComponent } from './p2/p2-block-ui-component';
import { BlockUiComponent as blockui__BlockUiComponent } from '@ciag/orchestra/blockui';
import { BoxComponent as box__BoxComponent } from '@ciag/orchestra/box';
import { BoxComponent as canonical__p2_p2_layout_components__BoxComponent } from './p2/p2-layout-components';
import { ButtonGroupComponent as button_group__ButtonGroupComponent } from '@ciag/orchestra/button-group';
import { ButtonGroupComponent as canonical__p2_p2_layout_components__ButtonGroupComponent } from './p2/p2-layout-components';
import { ButtonGroupComponent as buttongroup__ButtonGroupComponent } from '@ciag/orchestra/buttongroup';
import { CascadeSelectComponent as cascade_select__CascadeSelectComponent } from '@ciag/orchestra/cascade-select';
import { CascadeSelectComponent as canonical__p2_p2_cascade_select_component__CascadeSelectComponent } from './p2/p2-cascade-select-component';
import { CascadeSelectComponent as cascadeselect__CascadeSelectComponent } from '@ciag/orchestra/cascadeselect';
import { ChartComponent as chart__ChartComponent } from '@ciag/orchestra/chart';
import { ChartComponent as canonical__p2_p2_chart_editor_components__ChartComponent } from './p2/p2-chart-editor-components';
import { ChipsComponent as chips__ChipsComponent } from '@ciag/orchestra/chips';
import { TagsInputComponent as canonical__tags_input_tags_input_component__TagsInputComponent } from './tags-input/tags-input.component';
import { ColorPicker as colorpicker__ColorPicker } from '@ciag/orchestra/colorpicker';
import { ColorPickerComponent as canonical__color_picker_color_picker_component__ColorPickerComponent } from './color-picker/color-picker.component';
import { ColorPickerComponent as colorpicker__ColorPickerComponent } from '@ciag/orchestra/colorpicker';
import { CommandMenuComponent as command_menu__CommandMenuComponent } from '@ciag/orchestra/command-menu';
import { CommandMenuComponent as canonical__p2_p2_command_components__CommandMenuComponent } from './p2/p2-command-components';
import { CompareComponent as compare__CompareComponent } from '@ciag/orchestra/compare';
import { ImageCompareComponent as canonical__image_compare_image_compare_component__ImageCompareComponent } from './image-compare/image-compare.component';
import { ConfirmationService as confirm_dialog__ConfirmationService } from '@ciag/orchestra/confirm-dialog';
import { ConfirmationService as canonical__p2_p2_confirm_dialog_component__ConfirmationService } from './p2/p2-confirm-dialog-component';
import { ConfirmDialogComponent as confirm_dialog__ConfirmDialogComponent } from '@ciag/orchestra/confirm-dialog';
import { ConfirmDialogComponent as canonical__p2_p2_confirm_dialog_component__ConfirmDialogComponent } from './p2/p2-confirm-dialog-component';
import { ConfirmationService as confirmdialog__ConfirmationService } from '@ciag/orchestra/confirmdialog';
import { ConfirmDialogComponent as confirmdialog__ConfirmDialogComponent } from '@ciag/orchestra/confirmdialog';
import { ConfirmPopupComponent as confirmpopup__ConfirmPopupComponent } from '@ciag/orchestra/confirmpopup';
import { ConfirmPopupComponent as canonical__confirm_popup_confirm_popup_component__ConfirmPopupComponent } from './confirm-popup/confirm-popup.component';
import { ConfirmPopupService as confirmpopup__ConfirmPopupService } from '@ciag/orchestra/confirmpopup';
import { ConfirmPopupService as canonical__confirm_popup_confirm_popup_component__ConfirmPopupService } from './confirm-popup/confirm-popup.component';
import { ContainerComponent as container__ContainerComponent } from '@ciag/orchestra/container';
import { ContainerComponent as canonical__p2_p2_layout_components__ContainerComponent } from './p2/p2-layout-components';
import { ContextMenuComponent as contextmenu__ContextMenuComponent } from '@ciag/orchestra/contextmenu';
import { ContextMenuComponent as canonical__context_menu_context_menu_component__ContextMenuComponent } from './context-menu/context-menu.component';
import { DataTableComponent as data_table__DataTableComponent } from '@ciag/orchestra/data-table';
import { DataTableComponent as canonical__p2_p2_data_table_component__DataTableComponent } from './p2/p2-data-table-component';
import { DataViewComponent as dataview__DataViewComponent } from '@ciag/orchestra/dataview';
import { DataViewComponent as canonical__data_view_data_view_component__DataViewComponent } from './data-view/data-view.component';
import { DatePicker as datepicker__DatePicker } from '@ciag/orchestra/datepicker';
import { DatePickerComponent as canonical__date_picker_date_picker_component__DatePickerComponent } from './date-picker/date-picker.component';
import { DatepickerComponent as datepicker__DatepickerComponent } from '@ciag/orchestra/datepicker';
import { Dialog as dialog__Dialog } from '@ciag/orchestra/dialog';
import { ModalComponent as canonical__modal_modal_component__ModalComponent } from './modal/modal.component';
import { DialogComponent as dialog__DialogComponent } from '@ciag/orchestra/dialog';
import { DialogRef as dialog__DialogRef } from '@ciag/orchestra/dialog';
import { ModalRef as canonical__modal_modal_ref__ModalRef } from './modal/modal-ref';
import { DialogService as dialog__DialogService } from '@ciag/orchestra/dialog';
import { ModalService as canonical__modal_modal_service__ModalService } from './modal/modal.service';
import { DraggableDirective as dragdrop__DraggableDirective } from '@ciag/orchestra/dragdrop';
import { DraggableDirective as canonical__drag_drop_drag_drop_directive__DraggableDirective } from './drag-drop/drag-drop.directive';
import { DroppableDirective as dragdrop__DroppableDirective } from '@ciag/orchestra/dragdrop';
import { DroppableDirective as canonical__drag_drop_drag_drop_directive__DroppableDirective } from './drag-drop/drag-drop.directive';
import { DynamicDialogComponent as dynamic_dialog__DynamicDialogComponent } from '@ciag/orchestra/dynamic-dialog';
import { DynamicDialogRef as dynamic_dialog__DynamicDialogRef } from '@ciag/orchestra/dynamic-dialog';
import { DynamicDialogService as dynamic_dialog__DynamicDialogService } from '@ciag/orchestra/dynamic-dialog';
import { DynamicDialogComponent as dynamicdialog__DynamicDialogComponent } from '@ciag/orchestra/dynamicdialog';
import { DynamicDialogRef as dynamicdialog__DynamicDialogRef } from '@ciag/orchestra/dynamicdialog';
import { DynamicDialogService as dynamicdialog__DynamicDialogService } from '@ciag/orchestra/dynamicdialog';
import { FieldsetComponent as fieldset__FieldsetComponent } from '@ciag/orchestra/fieldset';
import { FieldsetComponent as canonical__p2_p2_primeng_gap_components__FieldsetComponent } from './p2/p2-primeng-gap-components';
import { FileUpload as file_upload__FileUpload } from '@ciag/orchestra/file-upload';
import { FileUploaderComponent as canonical__file_uploader_file_uploader_component__FileUploaderComponent } from './file-uploader/file-uploader.component';
import { FileUploadComponent as file_upload__FileUploadComponent } from '@ciag/orchestra/file-upload';
import { FileUpload as fileupload__FileUpload } from '@ciag/orchestra/fileupload';
import { FileUploadComponent as fileupload__FileUploadComponent } from '@ciag/orchestra/fileupload';
import { FlexComponent as flex__FlexComponent } from '@ciag/orchestra/flex';
import { FlexComponent as canonical__p2_p2_layout_components__FlexComponent } from './p2/p2-layout-components';
import { FloatingActionButtonComponent as floating_action_button__FloatingActionButtonComponent } from '@ciag/orchestra/floating-action-button';
import { FloatingActionButtonComponent as canonical__p2_p2_overlay_components__FloatingActionButtonComponent } from './p2/p2-overlay-components';
import { FluidComponent as fluid__FluidComponent } from '@ciag/orchestra/fluid';
import { FluidComponent as canonical__p2_p2_primeng_gap_components__FluidComponent } from './p2/p2-primeng-gap-components';
import { FocusTrapDirective as focus_trap__FocusTrapDirective } from '@ciag/orchestra/focus-trap';
import { FocusTrapDirective as canonical__p2_p2_utility_more__FocusTrapDirective } from './p2/p2-utility-more';
import { FocusTrapDirective as focustrap__FocusTrapDirective } from '@ciag/orchestra/focustrap';
import { GalleryComponent as gallery__GalleryComponent } from '@ciag/orchestra/gallery';
import { GalleriaComponent as canonical__galleria_galleria_component__GalleriaComponent } from './galleria/galleria.component';
import { GridComponent as grid__GridComponent } from '@ciag/orchestra/grid';
import { GridComponent as canonical__p2_p2_layout_components__GridComponent } from './p2/p2-layout-components';
import { IconFieldComponent as iconfield__IconFieldComponent } from '@ciag/orchestra/iconfield';
import { IconFieldComponent as canonical__icon_field_icon_field_component__IconFieldComponent } from './icon-field/icon-field.component';
import { IftaLabelComponent as iftalabel__IftaLabelComponent } from '@ciag/orchestra/iftalabel';
import { IftaLabelComponent as canonical__ifta_label_ifta_label_component__IftaLabelComponent } from './ifta-label/ifta-label.component';
import { ImageCompareComponent as imagecompare__ImageCompareComponent } from '@ciag/orchestra/imagecompare';
import { InplaceComponent as inplace__InplaceComponent } from '@ciag/orchestra/inplace';
import { InplaceComponent as canonical__p2_p2_inplace_component__InplaceComponent } from './p2/p2-inplace-component';
import { InputChipsComponent as input_chips__InputChipsComponent } from '@ciag/orchestra/input-chips';
import { InputColorComponent as input_color__InputColorComponent } from '@ciag/orchestra/input-color';
import { InputColorComponent as canonical__p2_p2_input_more__InputColorComponent } from './p2/p2-input-more';
import { InputIconComponent as input_icon__InputIconComponent } from '@ciag/orchestra/input-icon';
import { InputNumber as input_number__InputNumber } from '@ciag/orchestra/input-number';
import { NumberInputComponent as canonical__number_input_number_input_component__NumberInputComponent } from './number-input/number-input.component';
import { InputNumberComponent as input_number__InputNumberComponent } from '@ciag/orchestra/input-number';
import { InputOtp as input_otp__InputOtp } from '@ciag/orchestra/input-otp';
import { OtpInputComponent as canonical__otp_input_otp_input_component__OtpInputComponent } from './otp-input/otp-input.component';
import { InputOtpComponent as input_otp__InputOtpComponent } from '@ciag/orchestra/input-otp';
import { InputPassword as input_password__InputPassword } from '@ciag/orchestra/input-password';
import { PasswordComponent as canonical__password_password_component__PasswordComponent } from './password/password.component';
import { InputPasswordComponent as input_password__InputPasswordComponent } from '@ciag/orchestra/input-password';
import { InputTagsComponent as input_tags__InputTagsComponent } from '@ciag/orchestra/input-tags';
import { InputText as input_text__InputText } from '@ciag/orchestra/input-text';
import { InputComponent as canonical__input_input_component__InputComponent } from './input/input.component';
import { InputTextComponent as input_text__InputTextComponent } from '@ciag/orchestra/input-text';
import { InputTextareaComponent as input_textarea__InputTextareaComponent } from '@ciag/orchestra/input-textarea';
import { TextareaComponent as canonical__input_textarea_component__TextareaComponent } from './input/textarea.component';
import { InputGroupComponent as inputgroup__InputGroupComponent } from '@ciag/orchestra/inputgroup';
import { InputGroupComponent as canonical__input_group_input_group_component__InputGroupComponent } from './input-group/input-group.component';
import { InputGroupAddonComponent as inputgroupaddon__InputGroupAddonComponent } from '@ciag/orchestra/inputgroupaddon';
import { InputGroupAddonComponent as canonical__input_group_addon_input_group_addon_component__InputGroupAddonComponent } from './input-group-addon/input-group-addon.component';
import { InputIconComponent as inputicon__InputIconComponent } from '@ciag/orchestra/inputicon';
import { InputMaskDirective as inputmask__InputMaskDirective } from '@ciag/orchestra/inputmask';
import { InputMaskDirective as canonical__input_mask_input_mask_directive__InputMaskDirective } from './input-mask/input-mask.directive';
import { InputNumber as inputnumber__InputNumber } from '@ciag/orchestra/inputnumber';
import { InputNumberComponent as inputnumber__InputNumberComponent } from '@ciag/orchestra/inputnumber';
import { InputOtp as inputotp__InputOtp } from '@ciag/orchestra/inputotp';
import { InputOtpComponent as inputotp__InputOtpComponent } from '@ciag/orchestra/inputotp';
import { SwitchComponent as inputswitch__SwitchComponent } from '@ciag/orchestra/inputswitch';
import { SwitchComponent as canonical__switch_switch_component__SwitchComponent } from './switch/switch.component';
import { InputText as inputtext__InputText } from '@ciag/orchestra/inputtext';
import { InputTextComponent as inputtext__InputTextComponent } from '@ciag/orchestra/inputtext';
import { InputTextareaComponent as inputtextarea__InputTextareaComponent } from '@ciag/orchestra/inputtextarea';
import { KbdComponent as kbd__KbdComponent } from '@ciag/orchestra/kbd';
import { KbdComponent as canonical__p2_p2_layout_components__KbdComponent } from './p2/p2-layout-components';
import { KeyFilterDirective as keyfilter__KeyFilterDirective } from '@ciag/orchestra/keyfilter';
import { KeyFilterDirective as canonical__key_filter_key_filter_directive__KeyFilterDirective } from './key-filter/key-filter.directive';
import { LabelComponent as label__LabelComponent } from '@ciag/orchestra/label';
import { FormFieldComponent as canonical__form_field_form_field_component__FormFieldComponent } from './form-field/form-field.component';
import { LinkComponent as link__LinkComponent } from '@ciag/orchestra/link';
import { LinkComponent as canonical__p2_p2_layout_components__LinkComponent } from './p2/p2-layout-components';
import { MegaMenuComponent as megamenu__MegaMenuComponent } from '@ciag/orchestra/megamenu';
import { MegaMenuComponent as canonical__mega_menu_mega_menu_component__MegaMenuComponent } from './mega-menu/mega-menu.component';
import { MenuComponent as menu__MenuComponent } from '@ciag/orchestra/menu';
import { MenuComponent as canonical__p2_p2_advanced_components__MenuComponent } from './p2/p2-advanced-components';
import { MessageComponent as message__MessageComponent } from '@ciag/orchestra/message';
import { AlertComponent as canonical__alert_alert_component__AlertComponent } from './alert/alert.component';
import { MessagesComponent as message__MessagesComponent } from '@ciag/orchestra/message';
import { MessagesComponent as canonical__p2_p2_message_components__MessagesComponent } from './p2/p2-message-components';
import { MessageComponent as messages__MessageComponent } from '@ciag/orchestra/messages';
import { MessagesComponent as messages__MessagesComponent } from '@ciag/orchestra/messages';
import { MeterGroupComponent as metergroup__MeterGroupComponent } from '@ciag/orchestra/metergroup';
import { MeterGroupComponent as canonical__meter_group_meter_group_component__MeterGroupComponent } from './meter-group/meter-group.component';
import { MultiSelectComponent as multiselect__MultiSelectComponent } from '@ciag/orchestra/multiselect';
import { MultiSelectComponent as canonical__multi_select_multi_select_component__MultiSelectComponent } from './multi-select/multi-select.component';
import { OrderListComponent as orderlist__OrderListComponent } from '@ciag/orchestra/orderlist';
import { OrderListComponent as canonical__order_list_order_list_component__OrderListComponent } from './order-list/order-list.component';
import { OrganizationChartComponent as organizationchart__OrganizationChartComponent } from '@ciag/orchestra/organizationchart';
import { OrganizationChartComponent as canonical__organization_chart_organization_chart_component__OrganizationChartComponent } from './organization-chart/organization-chart.component';
import { OverlayComponent as overlay__OverlayComponent } from '@ciag/orchestra/overlay';
import { OverlayComponent as canonical__p2_p2_overlay_components__OverlayComponent } from './p2/p2-overlay-components';
import { OverlayBadgeComponent as overlay_badge__OverlayBadgeComponent } from '@ciag/orchestra/overlay-badge';
import { OverlayBadgeComponent as canonical__p2_p2_primeng_gap_components__OverlayBadgeComponent } from './p2/p2-primeng-gap-components';
import { OverlayBadgeComponent as overlaybadge__OverlayBadgeComponent } from '@ciag/orchestra/overlaybadge';
import { OverlayPanelComponent as overlaypanel__OverlayPanelComponent } from '@ciag/orchestra/overlaypanel';
import { OverlayPanelComponent as canonical__overlay_panel_overlay_panel_component__OverlayPanelComponent } from './overlay-panel/overlay-panel.component';
import { PaginationComponent as pagination__PaginationComponent } from '@ciag/orchestra/pagination';
import { PaginatorComponent as canonical__paginator_paginator_component__PaginatorComponent } from './paginator/paginator.component';
import { PanelComponent as panel__PanelComponent } from '@ciag/orchestra/panel';
import { PanelComponent as canonical__p2_p2_primeng_gap_components__PanelComponent } from './p2/p2-primeng-gap-components';
import { PanelMenuComponent as panelmenu__PanelMenuComponent } from '@ciag/orchestra/panelmenu';
import { PanelMenuComponent as canonical__panel_menu_panel_menu_component__PanelMenuComponent } from './panel-menu/panel-menu.component';
import { PickListComponent as picklist__PickListComponent } from '@ciag/orchestra/picklist';
import { PickListComponent as canonical__pick_list_pick_list_component__PickListComponent } from './pick-list/pick-list.component';
import { PortalComponent as portal__PortalComponent } from '@ciag/orchestra/portal';
import { PortalComponent as canonical__p2_p2_portal_component__PortalComponent } from './p2/p2-portal-component';
import { ProgressBarComponent as progress_bar__ProgressBarComponent } from '@ciag/orchestra/progress-bar';
import { ProgressBarComponent as canonical__progress_progress_bar_component__ProgressBarComponent } from './progress/progress-bar.component';
import { ProgressSpinner as progress_spinner__ProgressSpinner } from '@ciag/orchestra/progress-spinner';
import { ProgressSpinnerComponent as canonical__progress_progress_spinner_component__ProgressSpinnerComponent } from './progress/progress-spinner.component';
import { ProgressSpinnerComponent as progress_spinner__ProgressSpinnerComponent } from '@ciag/orchestra/progress-spinner';
import { ProgressBarComponent as progressbar__ProgressBarComponent } from '@ciag/orchestra/progressbar';
import { ProgressSpinner as progressspinner__ProgressSpinner } from '@ciag/orchestra/progressspinner';
import { ProgressSpinnerComponent as progressspinner__ProgressSpinnerComponent } from '@ciag/orchestra/progressspinner';
import { RadioButton as radio_button__RadioButton } from '@ciag/orchestra/radio-button';
import { RadioButtonComponent as canonical__radio_radio_button_component__RadioButtonComponent } from './radio/radio-button.component';
import { RadioButtonComponent as radio_button__RadioButtonComponent } from '@ciag/orchestra/radio-button';
import { RadioButton as radiobutton__RadioButton } from '@ciag/orchestra/radiobutton';
import { RadioButtonComponent as radiobutton__RadioButtonComponent } from '@ciag/orchestra/radiobutton';
import { RippleDirective as ripple__RippleDirective } from '@ciag/orchestra/ripple';
import { RippleDirective as canonical__p2_p2_utility_directives__RippleDirective } from './p2/p2-utility-directives';
import { ScrollPanelComponent as scroll_panel__ScrollPanelComponent } from '@ciag/orchestra/scroll-panel';
import { ScrollPanelComponent as canonical__p2_p2_dock_scroll_components__ScrollPanelComponent } from './p2/p2-dock-scroll-components';
import { ScrollTopComponent as scroll_top__ScrollTopComponent } from '@ciag/orchestra/scroll-top';
import { ScrollTopComponent as canonical__p2_p2_primeng_gap_components__ScrollTopComponent } from './p2/p2-primeng-gap-components';
import { ScrollerComponent as scroller__ScrollerComponent } from '@ciag/orchestra/scroller';
import { VirtualScrollerComponent as canonical__virtual_scroller_virtual_scroller_component__VirtualScrollerComponent } from './virtual-scroller/virtual-scroller.component';
import { ScrollPanelComponent as scrollpanel__ScrollPanelComponent } from '@ciag/orchestra/scrollpanel';
import { ScrollTopComponent as scrolltop__ScrollTopComponent } from '@ciag/orchestra/scrolltop';
import { SelectButtonComponent as selectbutton__SelectButtonComponent } from '@ciag/orchestra/selectbutton';
import { SelectButtonComponent as canonical__select_button_select_button_component__SelectButtonComponent } from './select-button/select-button.component';
import { SidebarComponent as sidebar__SidebarComponent } from '@ciag/orchestra/sidebar';
import { DrawerComponent as canonical__drawer_drawer_component__DrawerComponent } from './drawer/drawer.component';
import { SpaceComponent as space__SpaceComponent } from '@ciag/orchestra/space';
import { SpaceComponent as canonical__p2_p2_layout_components__SpaceComponent } from './p2/p2-layout-components';
import { SpeedDialComponent as speeddial__SpeedDialComponent } from '@ciag/orchestra/speeddial';
import { SpeedDialComponent as canonical__speed_dial_speed_dial_component__SpeedDialComponent } from './speed-dial/speed-dial.component';
import { SplitButtonComponent as splitbutton__SplitButtonComponent } from '@ciag/orchestra/splitbutton';
import { SplitButtonComponent as canonical__split_button_split_button_component__SplitButtonComponent } from './split-button/split-button.component';
import { SplitterComponent as splitter__SplitterComponent } from '@ciag/orchestra/splitter';
import { SplitterComponent as canonical__p2_p2_splitter_component__SplitterComponent } from './p2/p2-splitter-component';
import { StackComponent as stack__StackComponent } from '@ciag/orchestra/stack';
import { StackComponent as canonical__p2_p2_layout_components__StackComponent } from './p2/p2-layout-components';
import { StepsComponent as steps__StepsComponent } from '@ciag/orchestra/steps';
import { StepperComponent as canonical__stepper_stepper_component__StepperComponent } from './stepper/stepper.component';
import { StyleClassDirective as style_class__StyleClassDirective } from '@ciag/orchestra/style-class';
import { StyleClassDirective as canonical__p2_p2_utility_directives__StyleClassDirective } from './p2/p2-utility-directives';
import { StyleClassDirective as styleclass__StyleClassDirective } from '@ciag/orchestra/styleclass';
import { TabMenuComponent as tabmenu__TabMenuComponent } from '@ciag/orchestra/tabmenu';
import { TabMenuComponent as canonical__tab_menu_tab_menu_component__TabMenuComponent } from './tab-menu/tab-menu.component';
import { TabComponent as tabview__TabComponent } from '@ciag/orchestra/tabview';
import { TabComponent as canonical__tabs_tab_component__TabComponent } from './tabs/tab.component';
import { TabGroupComponent as tabview__TabGroupComponent } from '@ciag/orchestra/tabview';
import { TabGroupComponent as canonical__tabs_tab_group_component__TabGroupComponent } from './tabs/tab-group.component';
import { TextComponent as text__TextComponent } from '@ciag/orchestra/text';
import { TextComponent as canonical__p2_p2_layout_components__TextComponent } from './p2/p2-layout-components';
import { Textarea as textarea__Textarea } from '@ciag/orchestra/textarea';
import { TieredMenuComponent as tieredmenu__TieredMenuComponent } from '@ciag/orchestra/tieredmenu';
import { TieredMenuComponent as canonical__tiered_menu_tiered_menu_component__TieredMenuComponent } from './tiered-menu/tiered-menu.component';
import { ToggleSwitch as toggle_switch__ToggleSwitch } from '@ciag/orchestra/toggle-switch';
import { ToggleSwitchComponent as toggle_switch__ToggleSwitchComponent } from '@ciag/orchestra/toggle-switch';
import { ToggleButtonComponent as togglebutton__ToggleButtonComponent } from '@ciag/orchestra/togglebutton';
import { ToggleButtonComponent as canonical__toggle_button_toggle_button_component__ToggleButtonComponent } from './toggle-button/toggle-button.component';
import { ToggleSwitch as toggleswitch__ToggleSwitch } from '@ciag/orchestra/toggleswitch';
import { ToggleSwitchComponent as toggleswitch__ToggleSwitchComponent } from '@ciag/orchestra/toggleswitch';
import { TreeSelectComponent as treeselect__TreeSelectComponent } from '@ciag/orchestra/treeselect';
import { TreeSelectComponent as canonical__tree_select_tree_select_component__TreeSelectComponent } from './tree-select/tree-select.component';
import { TreeTableComponent as treetable__TreeTableComponent } from '@ciag/orchestra/treetable';
import { TreeTableComponent as canonical__tree_table_tree_table_component__TreeTableComponent } from './tree-table/tree-table.component';
import { TypographyComponent as typography__TypographyComponent } from '@ciag/orchestra/typography';
import { TypographyComponent as canonical__p2_p2_layout_components__TypographyComponent } from './p2/p2-layout-components';
import { UseStyleDirective as use_style__UseStyleDirective } from '@ciag/orchestra/use-style';
import { UseStyleDirective as canonical__p2_p2_utility_more__UseStyleDirective } from './p2/p2-utility-more';
import { UseStyleDirective as usestyle__UseStyleDirective } from '@ciag/orchestra/usestyle';
import { VisuallyHiddenComponent as visually_hidden__VisuallyHiddenComponent } from '@ciag/orchestra/visually-hidden';
import { VisuallyHiddenComponent as canonical__p2_p2_layout_components__VisuallyHiddenComponent } from './p2/p2-layout-components';
import type { AvatarItem as avatar_group__AvatarItem } from '@ciag/orchestra/avatar-group';
import type { AvatarItem as canonical__avatar_avatar_types__AvatarItem } from './avatar/avatar.types';
import type { AvatarItem as avatargroup__AvatarItem } from '@ciag/orchestra/avatargroup';
import type { BlockUiTarget as block_ui__BlockUiTarget } from '@ciag/orchestra/block-ui';
import type { BlockUiTarget as canonical__p2_p2_block_ui_component__BlockUiTarget } from './p2/p2-block-ui-component';
import type { BlockUiTarget as blockui__BlockUiTarget } from '@ciag/orchestra/blockui';
import type { CascadeOption as cascade_select__CascadeOption } from '@ciag/orchestra/cascade-select';
import type { CascadeOption as canonical__p2_p2_cascade_select_component__CascadeOption } from './p2/p2-cascade-select-component';
import type { CascadeOption as cascadeselect__CascadeOption } from '@ciag/orchestra/cascadeselect';
import type { ChartData as chart__ChartData } from '@ciag/orchestra/chart';
import type { ChartData as canonical__p2_p2_chart_editor_components__ChartData } from './p2/p2-chart-editor-components';
import type { ChartDataset as chart__ChartDataset } from '@ciag/orchestra/chart';
import type { ChartDataset as canonical__p2_p2_chart_editor_components__ChartDataset } from './p2/p2-chart-editor-components';
import type { ChartType as chart__ChartType } from '@ciag/orchestra/chart';
import type { ChartType as canonical__p2_p2_chart_editor_components__ChartType } from './p2/p2-chart-editor-components';
import type { ColorPickerFormat as colorpicker__ColorPickerFormat } from '@ciag/orchestra/colorpicker';
import type { ColorPickerFormat as canonical__color_picker_color_picker_component__ColorPickerFormat } from './color-picker/color-picker.component';
import type { ColorPickerSize as colorpicker__ColorPickerSize } from '@ciag/orchestra/colorpicker';
import type { ColorPickerSize as canonical__color_picker_color_picker_component__ColorPickerSize } from './color-picker/color-picker.component';
import type { CommandItem as command_menu__CommandItem } from '@ciag/orchestra/command-menu';
import type { CommandItem as canonical__p2_p2_command_components__CommandItem } from './p2/p2-command-components';
import type { ConfirmationRequest as confirm_dialog__ConfirmationRequest } from '@ciag/orchestra/confirm-dialog';
import type { ConfirmationRequest as canonical__p2_p2_confirm_dialog_component__ConfirmationRequest } from './p2/p2-confirm-dialog-component';
import type { ConfirmationRequest as confirmdialog__ConfirmationRequest } from '@ciag/orchestra/confirmdialog';
import type { PopupConfirmation as confirmpopup__PopupConfirmation } from '@ciag/orchestra/confirmpopup';
import type { PopupConfirmation as canonical__confirm_popup_confirm_popup_component__PopupConfirmation } from './confirm-popup/confirm-popup.component';
import type { ContextMenuItem as contextmenu__ContextMenuItem } from '@ciag/orchestra/contextmenu';
import type { ContextMenuItem as canonical__context_menu_context_menu_component__ContextMenuItem } from './context-menu/context-menu.component';
import type { DataTableColumn as data_table__DataTableColumn } from '@ciag/orchestra/data-table';
import type { DataTableColumn as canonical__p2_p2_data_table_component__DataTableColumn } from './p2/p2-data-table-component';
import type { SwitchChangeEvent as inputswitch__SwitchChangeEvent } from '@ciag/orchestra/inputswitch';
import type { SwitchChangeEvent as canonical__switch_switch_types__SwitchChangeEvent } from './switch/switch.types';
import type { SwitchLabelPosition as inputswitch__SwitchLabelPosition } from '@ciag/orchestra/inputswitch';
import type { SwitchLabelPosition as canonical__switch_switch_types__SwitchLabelPosition } from './switch/switch.types';
import type { SwitchSize as inputswitch__SwitchSize } from '@ciag/orchestra/inputswitch';
import type { SwitchSize as canonical__switch_switch_types__SwitchSize } from './switch/switch.types';
import type { PrimeMenuItem as megamenu__PrimeMenuItem } from '@ciag/orchestra/megamenu';
import type { PrimeMenuItem as canonical__internal_menu_item__PrimeMenuItem } from './internal/menu-item';
import type { MenuItem as menu__MenuItem } from '@ciag/orchestra/menu';
import type { MessageItem as message__MessageItem } from '@ciag/orchestra/message';
import type { P2Message as canonical__p2_p2_message_components__P2Message } from './p2/p2-message-components';
import type { MessageItem as messages__MessageItem } from '@ciag/orchestra/messages';
import type { MeterItem as metergroup__MeterItem } from '@ciag/orchestra/metergroup';
import type { MeterItem as canonical__meter_group_meter_group_component__MeterItem } from './meter-group/meter-group.component';
import type { MultiSelectOption as multiselect__MultiSelectOption } from '@ciag/orchestra/multiselect';
import type { P2Option as canonical__internal_p2_shared__P2Option } from './internal/p2-shared';
import type { OrganizationNode as organizationchart__OrganizationNode } from '@ciag/orchestra/organizationchart';
import type { OrganizationNode as canonical__organization_chart_organization_chart_component__OrganizationNode } from './organization-chart/organization-chart.component';
import type { PaginationPageEvent as pagination__PaginationPageEvent } from '@ciag/orchestra/pagination';
import type { PageChangeEvent as canonical__paginator_paginator_types__PageChangeEvent } from './paginator/paginator.types';
import type { PrimeMenuItem as panelmenu__PrimeMenuItem } from '@ciag/orchestra/panelmenu';
import type { P2Option as picklist__P2Option } from '@ciag/orchestra/picklist';
import type { SidebarPosition as sidebar__SidebarPosition } from '@ciag/orchestra/sidebar';
import type { DrawerPlacement as canonical__drawer_drawer_component__DrawerPlacement } from './drawer/drawer.component';
import type { SpeedDialAction as speeddial__SpeedDialAction } from '@ciag/orchestra/speeddial';
import type { SpeedDialAction as canonical__speed_dial_speed_dial_component__SpeedDialAction } from './speed-dial/speed-dial.component';
import type { SplitterPanel as splitter__SplitterPanel } from '@ciag/orchestra/splitter';
import type { SplitterPanel as canonical__p2_p2_splitter_component__SplitterPanel } from './p2/p2-splitter-component';
import type { TabMenuItem as tabmenu__TabMenuItem } from '@ciag/orchestra/tabmenu';
import type { TabMenuItem as canonical__tab_menu_tab_menu_component__TabMenuItem } from './tab-menu/tab-menu.component';
import type { TabChangeEvent as tabview__TabChangeEvent } from '@ciag/orchestra/tabview';
import type { TabChangeEvent as canonical__tabs_tabs_types__TabChangeEvent } from './tabs/tabs.types';
import type { TabIconPosition as tabview__TabIconPosition } from '@ciag/orchestra/tabview';
import type { TabIconPosition as canonical__tabs_tabs_types__TabIconPosition } from './tabs/tabs.types';
import type { TabSize as tabview__TabSize } from '@ciag/orchestra/tabview';
import type { TabSize as canonical__tabs_tabs_types__TabSize } from './tabs/tabs.types';
import type { TabVariant as tabview__TabVariant } from '@ciag/orchestra/tabview';
import type { TabVariant as canonical__tabs_tabs_types__TabVariant } from './tabs/tabs.types';
import type { PrimeMenuItem as tieredmenu__PrimeMenuItem } from '@ciag/orchestra/tieredmenu';
import type { TreeSelectNode as treeselect__TreeSelectNode } from '@ciag/orchestra/treeselect';
import type { TreeSelectNode as canonical__tree_select_tree_select_component__TreeSelectNode } from './tree-select/tree-select.component';
import type { HierarchyNode as treetable__HierarchyNode } from '@ciag/orchestra/treetable';
import type { HierarchyNode as canonical__tree_tree_component__HierarchyNode } from './tree/tree.component';
import type { TreeTableColumn as treetable__TreeTableColumn } from '@ciag/orchestra/treetable';
import type { TreeTableColumn as canonical__tree_table_tree_table_component__TreeTableColumn } from './tree-table/tree-table.component';
import type { TreeTableSortEvent as treetable__TreeTableSortEvent } from '@ciag/orchestra/treetable';
import type { TreeTableSortEvent as canonical__tree_table_tree_table_component__TreeTableSortEvent } from './tree-table/tree-table.component';

describe('Alias entry points (generated identity sweep)', () => {
  it('@ciag/orchestra/animate-on-scroll re-exports the canonical declarations', () => {
    expect(animate_on_scroll__AnimateOnScrollDirective)
      .withContext('animate-on-scroll#AnimateOnScrollDirective')
      .toBe(canonical__p2_p2_utility_more__AnimateOnScrollDirective);
  });

  it('@ciag/orchestra/animateonscroll re-exports the canonical declarations', () => {
    expect(animateonscroll__AnimateOnScrollDirective)
      .withContext('animateonscroll#AnimateOnScrollDirective')
      .toBe(canonical__p2_p2_utility_more__AnimateOnScrollDirective);
  });

  it('@ciag/orchestra/aspect-ratio re-exports the canonical declarations', () => {
    expect(aspect_ratio__AspectRatioComponent)
      .withContext('aspect-ratio#AspectRatioComponent')
      .toBe(canonical__p2_p2_layout_components__AspectRatioComponent);
  });

  it('@ciag/orchestra/autofocus re-exports the canonical declarations', () => {
    expect(autofocus__AutoFocusDirective)
      .withContext('autofocus#AutoFocusDirective')
      .toBe(canonical__p2_p2_input_more__AutoFocusDirective);
  });

  // avatar-group.AvatarItem === ./avatar/avatar.types#AvatarItem (type-only, checked at generation time)

  it('@ciag/orchestra/avatar-group re-exports the canonical declarations', () => {
    expect(avatar_group__AvatarGroupComponent)
      .withContext('avatar-group#AvatarGroupComponent')
      .toBe(canonical__avatar_avatar_group_component__AvatarGroupComponent);
  });

  // avatargroup.AvatarItem === ./avatar/avatar.types#AvatarItem (type-only, checked at generation time)

  it('@ciag/orchestra/avatargroup re-exports the canonical declarations', () => {
    expect(avatargroup__AvatarGroupComponent)
      .withContext('avatargroup#AvatarGroupComponent')
      .toBe(canonical__avatar_avatar_group_component__AvatarGroupComponent);
  });

  // block-ui.BlockUiTarget === ./p2/p2-block-ui-component#BlockUiTarget (type-only, checked at generation time)

  it('@ciag/orchestra/block-ui re-exports the canonical declarations', () => {
    expect(block_ui__BlockUiComponent)
      .withContext('block-ui#BlockUiComponent')
      .toBe(canonical__p2_p2_block_ui_component__BlockUiComponent);
  });

  // blockui.BlockUiTarget === ./p2/p2-block-ui-component#BlockUiTarget (type-only, checked at generation time)

  it('@ciag/orchestra/blockui re-exports the canonical declarations', () => {
    expect(blockui__BlockUiComponent)
      .withContext('blockui#BlockUiComponent')
      .toBe(canonical__p2_p2_block_ui_component__BlockUiComponent);
  });

  it('@ciag/orchestra/box re-exports the canonical declarations', () => {
    expect(box__BoxComponent)
      .withContext('box#BoxComponent')
      .toBe(canonical__p2_p2_layout_components__BoxComponent);
  });

  it('@ciag/orchestra/button-group re-exports the canonical declarations', () => {
    expect(button_group__ButtonGroupComponent)
      .withContext('button-group#ButtonGroupComponent')
      .toBe(canonical__p2_p2_layout_components__ButtonGroupComponent);
  });

  it('@ciag/orchestra/buttongroup re-exports the canonical declarations', () => {
    expect(buttongroup__ButtonGroupComponent)
      .withContext('buttongroup#ButtonGroupComponent')
      .toBe(canonical__p2_p2_layout_components__ButtonGroupComponent);
  });

  // cascade-select.CascadeOption === ./p2/p2-cascade-select-component#CascadeOption (type-only, checked at generation time)

  it('@ciag/orchestra/cascade-select re-exports the canonical declarations', () => {
    expect(cascade_select__CascadeSelectComponent)
      .withContext('cascade-select#CascadeSelectComponent')
      .toBe(canonical__p2_p2_cascade_select_component__CascadeSelectComponent);
  });

  // cascadeselect.CascadeOption === ./p2/p2-cascade-select-component#CascadeOption (type-only, checked at generation time)

  it('@ciag/orchestra/cascadeselect re-exports the canonical declarations', () => {
    expect(cascadeselect__CascadeSelectComponent)
      .withContext('cascadeselect#CascadeSelectComponent')
      .toBe(canonical__p2_p2_cascade_select_component__CascadeSelectComponent);
  });

  // chart.ChartData === ./p2/p2-chart-editor-components#ChartData (type-only, checked at generation time)

  // chart.ChartDataset === ./p2/p2-chart-editor-components#ChartDataset (type-only, checked at generation time)

  // chart.ChartType === ./p2/p2-chart-editor-components#ChartType (type-only, checked at generation time)

  it('@ciag/orchestra/chart re-exports the canonical declarations', () => {
    expect(chart__ChartComponent)
      .withContext('chart#ChartComponent')
      .toBe(canonical__p2_p2_chart_editor_components__ChartComponent);
  });

  it('@ciag/orchestra/chips re-exports the canonical declarations', () => {
    expect(chips__ChipsComponent)
      .withContext('chips#ChipsComponent')
      .toBe(canonical__tags_input_tags_input_component__TagsInputComponent);
  });

  // colorpicker.ColorPickerFormat === ./color-picker/color-picker.component#ColorPickerFormat (type-only, checked at generation time)

  // colorpicker.ColorPickerSize === ./color-picker/color-picker.component#ColorPickerSize (type-only, checked at generation time)

  it('@ciag/orchestra/colorpicker re-exports the canonical declarations', () => {
    expect(colorpicker__ColorPicker)
      .withContext('colorpicker#ColorPicker')
      .toBe(
        canonical__color_picker_color_picker_component__ColorPickerComponent,
      );
    expect(colorpicker__ColorPickerComponent)
      .withContext('colorpicker#ColorPickerComponent')
      .toBe(
        canonical__color_picker_color_picker_component__ColorPickerComponent,
      );
  });

  // command-menu.CommandItem === ./p2/p2-command-components#CommandItem (type-only, checked at generation time)

  it('@ciag/orchestra/command-menu re-exports the canonical declarations', () => {
    expect(command_menu__CommandMenuComponent)
      .withContext('command-menu#CommandMenuComponent')
      .toBe(canonical__p2_p2_command_components__CommandMenuComponent);
  });

  it('@ciag/orchestra/compare re-exports the canonical declarations', () => {
    expect(compare__CompareComponent)
      .withContext('compare#CompareComponent')
      .toBe(
        canonical__image_compare_image_compare_component__ImageCompareComponent,
      );
  });

  // confirm-dialog.ConfirmationRequest === ./p2/p2-confirm-dialog-component#ConfirmationRequest (type-only, checked at generation time)

  it('@ciag/orchestra/confirm-dialog re-exports the canonical declarations', () => {
    expect(confirm_dialog__ConfirmationService)
      .withContext('confirm-dialog#ConfirmationService')
      .toBe(canonical__p2_p2_confirm_dialog_component__ConfirmationService);
    expect(confirm_dialog__ConfirmDialogComponent)
      .withContext('confirm-dialog#ConfirmDialogComponent')
      .toBe(canonical__p2_p2_confirm_dialog_component__ConfirmDialogComponent);
  });

  // confirmdialog.ConfirmationRequest === ./p2/p2-confirm-dialog-component#ConfirmationRequest (type-only, checked at generation time)

  it('@ciag/orchestra/confirmdialog re-exports the canonical declarations', () => {
    expect(confirmdialog__ConfirmationService)
      .withContext('confirmdialog#ConfirmationService')
      .toBe(canonical__p2_p2_confirm_dialog_component__ConfirmationService);
    expect(confirmdialog__ConfirmDialogComponent)
      .withContext('confirmdialog#ConfirmDialogComponent')
      .toBe(canonical__p2_p2_confirm_dialog_component__ConfirmDialogComponent);
  });

  // confirmpopup.PopupConfirmation === ./confirm-popup/confirm-popup.component#PopupConfirmation (type-only, checked at generation time)

  it('@ciag/orchestra/confirmpopup re-exports the canonical declarations', () => {
    expect(confirmpopup__ConfirmPopupComponent)
      .withContext('confirmpopup#ConfirmPopupComponent')
      .toBe(
        canonical__confirm_popup_confirm_popup_component__ConfirmPopupComponent,
      );
    expect(confirmpopup__ConfirmPopupService)
      .withContext('confirmpopup#ConfirmPopupService')
      .toBe(
        canonical__confirm_popup_confirm_popup_component__ConfirmPopupService,
      );
  });

  it('@ciag/orchestra/container re-exports the canonical declarations', () => {
    expect(container__ContainerComponent)
      .withContext('container#ContainerComponent')
      .toBe(canonical__p2_p2_layout_components__ContainerComponent);
  });

  // contextmenu.ContextMenuItem === ./context-menu/context-menu.component#ContextMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/contextmenu re-exports the canonical declarations', () => {
    expect(contextmenu__ContextMenuComponent)
      .withContext('contextmenu#ContextMenuComponent')
      .toBe(
        canonical__context_menu_context_menu_component__ContextMenuComponent,
      );
  });

  // data-table.DataTableColumn === ./p2/p2-data-table-component#DataTableColumn (type-only, checked at generation time)

  it('@ciag/orchestra/data-table re-exports the canonical declarations', () => {
    expect(data_table__DataTableComponent)
      .withContext('data-table#DataTableComponent')
      .toBe(canonical__p2_p2_data_table_component__DataTableComponent);
  });

  it('@ciag/orchestra/dataview re-exports the canonical declarations', () => {
    expect(dataview__DataViewComponent)
      .withContext('dataview#DataViewComponent')
      .toBe(canonical__data_view_data_view_component__DataViewComponent);
  });

  it('@ciag/orchestra/datepicker re-exports the canonical declarations', () => {
    expect(datepicker__DatePicker)
      .withContext('datepicker#DatePicker')
      .toBe(canonical__date_picker_date_picker_component__DatePickerComponent);
    expect(datepicker__DatepickerComponent)
      .withContext('datepicker#DatepickerComponent')
      .toBe(canonical__date_picker_date_picker_component__DatePickerComponent);
  });

  it('@ciag/orchestra/dialog re-exports the canonical declarations', () => {
    expect(dialog__Dialog)
      .withContext('dialog#Dialog')
      .toBe(canonical__modal_modal_component__ModalComponent);
    expect(dialog__DialogComponent)
      .withContext('dialog#DialogComponent')
      .toBe(canonical__modal_modal_component__ModalComponent);
    expect(dialog__DialogRef)
      .withContext('dialog#DialogRef')
      .toBe(canonical__modal_modal_ref__ModalRef);
    expect(dialog__DialogService)
      .withContext('dialog#DialogService')
      .toBe(canonical__modal_modal_service__ModalService);
  });

  it('@ciag/orchestra/dragdrop re-exports the canonical declarations', () => {
    expect(dragdrop__DraggableDirective)
      .withContext('dragdrop#DraggableDirective')
      .toBe(canonical__drag_drop_drag_drop_directive__DraggableDirective);
    expect(dragdrop__DroppableDirective)
      .withContext('dragdrop#DroppableDirective')
      .toBe(canonical__drag_drop_drag_drop_directive__DroppableDirective);
  });

  it('@ciag/orchestra/dynamic-dialog re-exports the canonical declarations', () => {
    expect(dynamic_dialog__DynamicDialogComponent)
      .withContext('dynamic-dialog#DynamicDialogComponent')
      .toBe(canonical__modal_modal_component__ModalComponent);
    expect(dynamic_dialog__DynamicDialogRef)
      .withContext('dynamic-dialog#DynamicDialogRef')
      .toBe(canonical__modal_modal_ref__ModalRef);
    expect(dynamic_dialog__DynamicDialogService)
      .withContext('dynamic-dialog#DynamicDialogService')
      .toBe(canonical__modal_modal_service__ModalService);
  });

  it('@ciag/orchestra/dynamicdialog re-exports the canonical declarations', () => {
    expect(dynamicdialog__DynamicDialogComponent)
      .withContext('dynamicdialog#DynamicDialogComponent')
      .toBe(canonical__modal_modal_component__ModalComponent);
    expect(dynamicdialog__DynamicDialogRef)
      .withContext('dynamicdialog#DynamicDialogRef')
      .toBe(canonical__modal_modal_ref__ModalRef);
    expect(dynamicdialog__DynamicDialogService)
      .withContext('dynamicdialog#DynamicDialogService')
      .toBe(canonical__modal_modal_service__ModalService);
  });

  it('@ciag/orchestra/fieldset re-exports the canonical declarations', () => {
    expect(fieldset__FieldsetComponent)
      .withContext('fieldset#FieldsetComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__FieldsetComponent);
  });

  it('@ciag/orchestra/file-upload re-exports the canonical declarations', () => {
    expect(file_upload__FileUpload)
      .withContext('file-upload#FileUpload')
      .toBe(
        canonical__file_uploader_file_uploader_component__FileUploaderComponent,
      );
    expect(file_upload__FileUploadComponent)
      .withContext('file-upload#FileUploadComponent')
      .toBe(
        canonical__file_uploader_file_uploader_component__FileUploaderComponent,
      );
  });

  it('@ciag/orchestra/fileupload re-exports the canonical declarations', () => {
    expect(fileupload__FileUpload)
      .withContext('fileupload#FileUpload')
      .toBe(
        canonical__file_uploader_file_uploader_component__FileUploaderComponent,
      );
    expect(fileupload__FileUploadComponent)
      .withContext('fileupload#FileUploadComponent')
      .toBe(
        canonical__file_uploader_file_uploader_component__FileUploaderComponent,
      );
  });

  it('@ciag/orchestra/flex re-exports the canonical declarations', () => {
    expect(flex__FlexComponent)
      .withContext('flex#FlexComponent')
      .toBe(canonical__p2_p2_layout_components__FlexComponent);
  });

  it('@ciag/orchestra/floating-action-button re-exports the canonical declarations', () => {
    expect(floating_action_button__FloatingActionButtonComponent)
      .withContext('floating-action-button#FloatingActionButtonComponent')
      .toBe(canonical__p2_p2_overlay_components__FloatingActionButtonComponent);
  });

  it('@ciag/orchestra/fluid re-exports the canonical declarations', () => {
    expect(fluid__FluidComponent)
      .withContext('fluid#FluidComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__FluidComponent);
  });

  it('@ciag/orchestra/focus-trap re-exports the canonical declarations', () => {
    expect(focus_trap__FocusTrapDirective)
      .withContext('focus-trap#FocusTrapDirective')
      .toBe(canonical__p2_p2_utility_more__FocusTrapDirective);
  });

  it('@ciag/orchestra/focustrap re-exports the canonical declarations', () => {
    expect(focustrap__FocusTrapDirective)
      .withContext('focustrap#FocusTrapDirective')
      .toBe(canonical__p2_p2_utility_more__FocusTrapDirective);
  });

  it('@ciag/orchestra/gallery re-exports the canonical declarations', () => {
    expect(gallery__GalleryComponent)
      .withContext('gallery#GalleryComponent')
      .toBe(canonical__galleria_galleria_component__GalleriaComponent);
  });

  it('@ciag/orchestra/grid re-exports the canonical declarations', () => {
    expect(grid__GridComponent)
      .withContext('grid#GridComponent')
      .toBe(canonical__p2_p2_layout_components__GridComponent);
  });

  it('@ciag/orchestra/iconfield re-exports the canonical declarations', () => {
    expect(iconfield__IconFieldComponent)
      .withContext('iconfield#IconFieldComponent')
      .toBe(canonical__icon_field_icon_field_component__IconFieldComponent);
  });

  it('@ciag/orchestra/iftalabel re-exports the canonical declarations', () => {
    expect(iftalabel__IftaLabelComponent)
      .withContext('iftalabel#IftaLabelComponent')
      .toBe(canonical__ifta_label_ifta_label_component__IftaLabelComponent);
  });

  it('@ciag/orchestra/imagecompare re-exports the canonical declarations', () => {
    expect(imagecompare__ImageCompareComponent)
      .withContext('imagecompare#ImageCompareComponent')
      .toBe(
        canonical__image_compare_image_compare_component__ImageCompareComponent,
      );
  });

  it('@ciag/orchestra/inplace re-exports the canonical declarations', () => {
    expect(inplace__InplaceComponent)
      .withContext('inplace#InplaceComponent')
      .toBe(canonical__p2_p2_inplace_component__InplaceComponent);
  });

  it('@ciag/orchestra/input-chips re-exports the canonical declarations', () => {
    expect(input_chips__InputChipsComponent)
      .withContext('input-chips#InputChipsComponent')
      .toBe(canonical__tags_input_tags_input_component__TagsInputComponent);
  });

  it('@ciag/orchestra/input-color re-exports the canonical declarations', () => {
    expect(input_color__InputColorComponent)
      .withContext('input-color#InputColorComponent')
      .toBe(canonical__p2_p2_input_more__InputColorComponent);
  });

  it('@ciag/orchestra/input-icon re-exports the canonical declarations', () => {
    expect(input_icon__InputIconComponent)
      .withContext('input-icon#InputIconComponent')
      .toBe(canonical__icon_field_icon_field_component__IconFieldComponent);
  });

  it('@ciag/orchestra/input-number re-exports the canonical declarations', () => {
    expect(input_number__InputNumber)
      .withContext('input-number#InputNumber')
      .toBe(
        canonical__number_input_number_input_component__NumberInputComponent,
      );
    expect(input_number__InputNumberComponent)
      .withContext('input-number#InputNumberComponent')
      .toBe(
        canonical__number_input_number_input_component__NumberInputComponent,
      );
  });

  it('@ciag/orchestra/input-otp re-exports the canonical declarations', () => {
    expect(input_otp__InputOtp)
      .withContext('input-otp#InputOtp')
      .toBe(canonical__otp_input_otp_input_component__OtpInputComponent);
    expect(input_otp__InputOtpComponent)
      .withContext('input-otp#InputOtpComponent')
      .toBe(canonical__otp_input_otp_input_component__OtpInputComponent);
  });

  it('@ciag/orchestra/input-password re-exports the canonical declarations', () => {
    expect(input_password__InputPassword)
      .withContext('input-password#InputPassword')
      .toBe(canonical__password_password_component__PasswordComponent);
    expect(input_password__InputPasswordComponent)
      .withContext('input-password#InputPasswordComponent')
      .toBe(canonical__password_password_component__PasswordComponent);
  });

  it('@ciag/orchestra/input-tags re-exports the canonical declarations', () => {
    expect(input_tags__InputTagsComponent)
      .withContext('input-tags#InputTagsComponent')
      .toBe(canonical__tags_input_tags_input_component__TagsInputComponent);
  });

  it('@ciag/orchestra/input-text re-exports the canonical declarations', () => {
    expect(input_text__InputText)
      .withContext('input-text#InputText')
      .toBe(canonical__input_input_component__InputComponent);
    expect(input_text__InputTextComponent)
      .withContext('input-text#InputTextComponent')
      .toBe(canonical__input_input_component__InputComponent);
  });

  it('@ciag/orchestra/input-textarea re-exports the canonical declarations', () => {
    expect(input_textarea__InputTextareaComponent)
      .withContext('input-textarea#InputTextareaComponent')
      .toBe(canonical__input_textarea_component__TextareaComponent);
  });

  it('@ciag/orchestra/inputgroup re-exports the canonical declarations', () => {
    expect(inputgroup__InputGroupComponent)
      .withContext('inputgroup#InputGroupComponent')
      .toBe(canonical__input_group_input_group_component__InputGroupComponent);
  });

  it('@ciag/orchestra/inputgroupaddon re-exports the canonical declarations', () => {
    expect(inputgroupaddon__InputGroupAddonComponent)
      .withContext('inputgroupaddon#InputGroupAddonComponent')
      .toBe(
        canonical__input_group_addon_input_group_addon_component__InputGroupAddonComponent,
      );
  });

  it('@ciag/orchestra/inputicon re-exports the canonical declarations', () => {
    expect(inputicon__InputIconComponent)
      .withContext('inputicon#InputIconComponent')
      .toBe(canonical__icon_field_icon_field_component__IconFieldComponent);
  });

  it('@ciag/orchestra/inputmask re-exports the canonical declarations', () => {
    expect(inputmask__InputMaskDirective)
      .withContext('inputmask#InputMaskDirective')
      .toBe(canonical__input_mask_input_mask_directive__InputMaskDirective);
  });

  it('@ciag/orchestra/inputnumber re-exports the canonical declarations', () => {
    expect(inputnumber__InputNumber)
      .withContext('inputnumber#InputNumber')
      .toBe(
        canonical__number_input_number_input_component__NumberInputComponent,
      );
    expect(inputnumber__InputNumberComponent)
      .withContext('inputnumber#InputNumberComponent')
      .toBe(
        canonical__number_input_number_input_component__NumberInputComponent,
      );
  });

  it('@ciag/orchestra/inputotp re-exports the canonical declarations', () => {
    expect(inputotp__InputOtp)
      .withContext('inputotp#InputOtp')
      .toBe(canonical__otp_input_otp_input_component__OtpInputComponent);
    expect(inputotp__InputOtpComponent)
      .withContext('inputotp#InputOtpComponent')
      .toBe(canonical__otp_input_otp_input_component__OtpInputComponent);
  });

  // inputswitch.SwitchChangeEvent === ./switch/switch.types#SwitchChangeEvent (type-only, checked at generation time)

  // inputswitch.SwitchLabelPosition === ./switch/switch.types#SwitchLabelPosition (type-only, checked at generation time)

  // inputswitch.SwitchSize === ./switch/switch.types#SwitchSize (type-only, checked at generation time)

  it('@ciag/orchestra/inputswitch re-exports the canonical declarations', () => {
    expect(inputswitch__SwitchComponent)
      .withContext('inputswitch#SwitchComponent')
      .toBe(canonical__switch_switch_component__SwitchComponent);
  });

  it('@ciag/orchestra/inputtext re-exports the canonical declarations', () => {
    expect(inputtext__InputText)
      .withContext('inputtext#InputText')
      .toBe(canonical__input_input_component__InputComponent);
    expect(inputtext__InputTextComponent)
      .withContext('inputtext#InputTextComponent')
      .toBe(canonical__input_input_component__InputComponent);
  });

  it('@ciag/orchestra/inputtextarea re-exports the canonical declarations', () => {
    expect(inputtextarea__InputTextareaComponent)
      .withContext('inputtextarea#InputTextareaComponent')
      .toBe(canonical__input_textarea_component__TextareaComponent);
  });

  it('@ciag/orchestra/kbd re-exports the canonical declarations', () => {
    expect(kbd__KbdComponent)
      .withContext('kbd#KbdComponent')
      .toBe(canonical__p2_p2_layout_components__KbdComponent);
  });

  it('@ciag/orchestra/keyfilter re-exports the canonical declarations', () => {
    expect(keyfilter__KeyFilterDirective)
      .withContext('keyfilter#KeyFilterDirective')
      .toBe(canonical__key_filter_key_filter_directive__KeyFilterDirective);
  });

  it('@ciag/orchestra/label re-exports the canonical declarations', () => {
    expect(label__LabelComponent)
      .withContext('label#LabelComponent')
      .toBe(canonical__form_field_form_field_component__FormFieldComponent);
  });

  it('@ciag/orchestra/link re-exports the canonical declarations', () => {
    expect(link__LinkComponent)
      .withContext('link#LinkComponent')
      .toBe(canonical__p2_p2_layout_components__LinkComponent);
  });

  // megamenu.PrimeMenuItem === ./internal/menu-item#PrimeMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/megamenu re-exports the canonical declarations', () => {
    expect(megamenu__MegaMenuComponent)
      .withContext('megamenu#MegaMenuComponent')
      .toBe(canonical__mega_menu_mega_menu_component__MegaMenuComponent);
  });

  // menu.MenuItem === ./internal/menu-item#PrimeMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/menu re-exports the canonical declarations', () => {
    expect(menu__MenuComponent)
      .withContext('menu#MenuComponent')
      .toBe(canonical__p2_p2_advanced_components__MenuComponent);
  });

  // message.MessageItem === ./p2/p2-message-components#P2Message (type-only, checked at generation time)

  it('@ciag/orchestra/message re-exports the canonical declarations', () => {
    expect(message__MessageComponent)
      .withContext('message#MessageComponent')
      .toBe(canonical__alert_alert_component__AlertComponent);
    expect(message__MessagesComponent)
      .withContext('message#MessagesComponent')
      .toBe(canonical__p2_p2_message_components__MessagesComponent);
  });

  // messages.MessageItem === ./p2/p2-message-components#P2Message (type-only, checked at generation time)

  it('@ciag/orchestra/messages re-exports the canonical declarations', () => {
    expect(messages__MessageComponent)
      .withContext('messages#MessageComponent')
      .toBe(canonical__alert_alert_component__AlertComponent);
    expect(messages__MessagesComponent)
      .withContext('messages#MessagesComponent')
      .toBe(canonical__p2_p2_message_components__MessagesComponent);
  });

  // metergroup.MeterItem === ./meter-group/meter-group.component#MeterItem (type-only, checked at generation time)

  it('@ciag/orchestra/metergroup re-exports the canonical declarations', () => {
    expect(metergroup__MeterGroupComponent)
      .withContext('metergroup#MeterGroupComponent')
      .toBe(canonical__meter_group_meter_group_component__MeterGroupComponent);
  });

  // multiselect.MultiSelectOption === ./internal/p2-shared#P2Option (type-only, checked at generation time)

  it('@ciag/orchestra/multiselect re-exports the canonical declarations', () => {
    expect(multiselect__MultiSelectComponent)
      .withContext('multiselect#MultiSelectComponent')
      .toBe(
        canonical__multi_select_multi_select_component__MultiSelectComponent,
      );
  });

  it('@ciag/orchestra/orderlist re-exports the canonical declarations', () => {
    expect(orderlist__OrderListComponent)
      .withContext('orderlist#OrderListComponent')
      .toBe(canonical__order_list_order_list_component__OrderListComponent);
  });

  // organizationchart.OrganizationNode === ./organization-chart/organization-chart.component#OrganizationNode (type-only, checked at generation time)

  it('@ciag/orchestra/organizationchart re-exports the canonical declarations', () => {
    expect(organizationchart__OrganizationChartComponent)
      .withContext('organizationchart#OrganizationChartComponent')
      .toBe(
        canonical__organization_chart_organization_chart_component__OrganizationChartComponent,
      );
  });

  it('@ciag/orchestra/overlay re-exports the canonical declarations', () => {
    expect(overlay__OverlayComponent)
      .withContext('overlay#OverlayComponent')
      .toBe(canonical__p2_p2_overlay_components__OverlayComponent);
  });

  it('@ciag/orchestra/overlay-badge re-exports the canonical declarations', () => {
    expect(overlay_badge__OverlayBadgeComponent)
      .withContext('overlay-badge#OverlayBadgeComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__OverlayBadgeComponent);
  });

  it('@ciag/orchestra/overlaybadge re-exports the canonical declarations', () => {
    expect(overlaybadge__OverlayBadgeComponent)
      .withContext('overlaybadge#OverlayBadgeComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__OverlayBadgeComponent);
  });

  it('@ciag/orchestra/overlaypanel re-exports the canonical declarations', () => {
    expect(overlaypanel__OverlayPanelComponent)
      .withContext('overlaypanel#OverlayPanelComponent')
      .toBe(
        canonical__overlay_panel_overlay_panel_component__OverlayPanelComponent,
      );
  });

  // pagination.PaginationPageEvent === ./paginator/paginator.types#PageChangeEvent (type-only, checked at generation time)

  it('@ciag/orchestra/pagination re-exports the canonical declarations', () => {
    expect(pagination__PaginationComponent)
      .withContext('pagination#PaginationComponent')
      .toBe(canonical__paginator_paginator_component__PaginatorComponent);
  });

  it('@ciag/orchestra/panel re-exports the canonical declarations', () => {
    expect(panel__PanelComponent)
      .withContext('panel#PanelComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__PanelComponent);
  });

  // panelmenu.PrimeMenuItem === ./internal/menu-item#PrimeMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/panelmenu re-exports the canonical declarations', () => {
    expect(panelmenu__PanelMenuComponent)
      .withContext('panelmenu#PanelMenuComponent')
      .toBe(canonical__panel_menu_panel_menu_component__PanelMenuComponent);
  });

  // picklist.P2Option === ./internal/p2-shared#P2Option (type-only, checked at generation time)

  it('@ciag/orchestra/picklist re-exports the canonical declarations', () => {
    expect(picklist__PickListComponent)
      .withContext('picklist#PickListComponent')
      .toBe(canonical__pick_list_pick_list_component__PickListComponent);
  });

  it('@ciag/orchestra/portal re-exports the canonical declarations', () => {
    expect(portal__PortalComponent)
      .withContext('portal#PortalComponent')
      .toBe(canonical__p2_p2_portal_component__PortalComponent);
  });

  it('@ciag/orchestra/progress-bar re-exports the canonical declarations', () => {
    expect(progress_bar__ProgressBarComponent)
      .withContext('progress-bar#ProgressBarComponent')
      .toBe(canonical__progress_progress_bar_component__ProgressBarComponent);
  });

  it('@ciag/orchestra/progress-spinner re-exports the canonical declarations', () => {
    expect(progress_spinner__ProgressSpinner)
      .withContext('progress-spinner#ProgressSpinner')
      .toBe(
        canonical__progress_progress_spinner_component__ProgressSpinnerComponent,
      );
    expect(progress_spinner__ProgressSpinnerComponent)
      .withContext('progress-spinner#ProgressSpinnerComponent')
      .toBe(
        canonical__progress_progress_spinner_component__ProgressSpinnerComponent,
      );
  });

  it('@ciag/orchestra/progressbar re-exports the canonical declarations', () => {
    expect(progressbar__ProgressBarComponent)
      .withContext('progressbar#ProgressBarComponent')
      .toBe(canonical__progress_progress_bar_component__ProgressBarComponent);
  });

  it('@ciag/orchestra/progressspinner re-exports the canonical declarations', () => {
    expect(progressspinner__ProgressSpinner)
      .withContext('progressspinner#ProgressSpinner')
      .toBe(
        canonical__progress_progress_spinner_component__ProgressSpinnerComponent,
      );
    expect(progressspinner__ProgressSpinnerComponent)
      .withContext('progressspinner#ProgressSpinnerComponent')
      .toBe(
        canonical__progress_progress_spinner_component__ProgressSpinnerComponent,
      );
  });

  it('@ciag/orchestra/radio-button re-exports the canonical declarations', () => {
    expect(radio_button__RadioButton)
      .withContext('radio-button#RadioButton')
      .toBe(canonical__radio_radio_button_component__RadioButtonComponent);
    expect(radio_button__RadioButtonComponent)
      .withContext('radio-button#RadioButtonComponent')
      .toBe(canonical__radio_radio_button_component__RadioButtonComponent);
  });

  it('@ciag/orchestra/radiobutton re-exports the canonical declarations', () => {
    expect(radiobutton__RadioButton)
      .withContext('radiobutton#RadioButton')
      .toBe(canonical__radio_radio_button_component__RadioButtonComponent);
    expect(radiobutton__RadioButtonComponent)
      .withContext('radiobutton#RadioButtonComponent')
      .toBe(canonical__radio_radio_button_component__RadioButtonComponent);
  });

  it('@ciag/orchestra/ripple re-exports the canonical declarations', () => {
    expect(ripple__RippleDirective)
      .withContext('ripple#RippleDirective')
      .toBe(canonical__p2_p2_utility_directives__RippleDirective);
  });

  it('@ciag/orchestra/scroll-panel re-exports the canonical declarations', () => {
    expect(scroll_panel__ScrollPanelComponent)
      .withContext('scroll-panel#ScrollPanelComponent')
      .toBe(canonical__p2_p2_dock_scroll_components__ScrollPanelComponent);
  });

  it('@ciag/orchestra/scroll-top re-exports the canonical declarations', () => {
    expect(scroll_top__ScrollTopComponent)
      .withContext('scroll-top#ScrollTopComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__ScrollTopComponent);
  });

  it('@ciag/orchestra/scroller re-exports the canonical declarations', () => {
    expect(scroller__ScrollerComponent)
      .withContext('scroller#ScrollerComponent')
      .toBe(
        canonical__virtual_scroller_virtual_scroller_component__VirtualScrollerComponent,
      );
  });

  it('@ciag/orchestra/scrollpanel re-exports the canonical declarations', () => {
    expect(scrollpanel__ScrollPanelComponent)
      .withContext('scrollpanel#ScrollPanelComponent')
      .toBe(canonical__p2_p2_dock_scroll_components__ScrollPanelComponent);
  });

  it('@ciag/orchestra/scrolltop re-exports the canonical declarations', () => {
    expect(scrolltop__ScrollTopComponent)
      .withContext('scrolltop#ScrollTopComponent')
      .toBe(canonical__p2_p2_primeng_gap_components__ScrollTopComponent);
  });

  it('@ciag/orchestra/selectbutton re-exports the canonical declarations', () => {
    expect(selectbutton__SelectButtonComponent)
      .withContext('selectbutton#SelectButtonComponent')
      .toBe(
        canonical__select_button_select_button_component__SelectButtonComponent,
      );
  });

  // sidebar.SidebarPosition === ./drawer/drawer.component#DrawerPlacement (type-only, checked at generation time)

  it('@ciag/orchestra/sidebar re-exports the canonical declarations', () => {
    expect(sidebar__SidebarComponent)
      .withContext('sidebar#SidebarComponent')
      .toBe(canonical__drawer_drawer_component__DrawerComponent);
  });

  it('@ciag/orchestra/space re-exports the canonical declarations', () => {
    expect(space__SpaceComponent)
      .withContext('space#SpaceComponent')
      .toBe(canonical__p2_p2_layout_components__SpaceComponent);
  });

  // speeddial.SpeedDialAction === ./speed-dial/speed-dial.component#SpeedDialAction (type-only, checked at generation time)

  it('@ciag/orchestra/speeddial re-exports the canonical declarations', () => {
    expect(speeddial__SpeedDialComponent)
      .withContext('speeddial#SpeedDialComponent')
      .toBe(canonical__speed_dial_speed_dial_component__SpeedDialComponent);
  });

  it('@ciag/orchestra/splitbutton re-exports the canonical declarations', () => {
    expect(splitbutton__SplitButtonComponent)
      .withContext('splitbutton#SplitButtonComponent')
      .toBe(
        canonical__split_button_split_button_component__SplitButtonComponent,
      );
  });

  // splitter.SplitterPanel === ./p2/p2-splitter-component#SplitterPanel (type-only, checked at generation time)

  it('@ciag/orchestra/splitter re-exports the canonical declarations', () => {
    expect(splitter__SplitterComponent)
      .withContext('splitter#SplitterComponent')
      .toBe(canonical__p2_p2_splitter_component__SplitterComponent);
  });

  it('@ciag/orchestra/stack re-exports the canonical declarations', () => {
    expect(stack__StackComponent)
      .withContext('stack#StackComponent')
      .toBe(canonical__p2_p2_layout_components__StackComponent);
  });

  it('@ciag/orchestra/steps re-exports the canonical declarations', () => {
    expect(steps__StepsComponent)
      .withContext('steps#StepsComponent')
      .toBe(canonical__stepper_stepper_component__StepperComponent);
  });

  it('@ciag/orchestra/style-class re-exports the canonical declarations', () => {
    expect(style_class__StyleClassDirective)
      .withContext('style-class#StyleClassDirective')
      .toBe(canonical__p2_p2_utility_directives__StyleClassDirective);
  });

  it('@ciag/orchestra/styleclass re-exports the canonical declarations', () => {
    expect(styleclass__StyleClassDirective)
      .withContext('styleclass#StyleClassDirective')
      .toBe(canonical__p2_p2_utility_directives__StyleClassDirective);
  });

  // tabmenu.TabMenuItem === ./tab-menu/tab-menu.component#TabMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/tabmenu re-exports the canonical declarations', () => {
    expect(tabmenu__TabMenuComponent)
      .withContext('tabmenu#TabMenuComponent')
      .toBe(canonical__tab_menu_tab_menu_component__TabMenuComponent);
  });

  // tabview.TabChangeEvent === ./tabs/tabs.types#TabChangeEvent (type-only, checked at generation time)

  // tabview.TabIconPosition === ./tabs/tabs.types#TabIconPosition (type-only, checked at generation time)

  // tabview.TabSize === ./tabs/tabs.types#TabSize (type-only, checked at generation time)

  // tabview.TabVariant === ./tabs/tabs.types#TabVariant (type-only, checked at generation time)

  it('@ciag/orchestra/tabview re-exports the canonical declarations', () => {
    expect(tabview__TabComponent)
      .withContext('tabview#TabComponent')
      .toBe(canonical__tabs_tab_component__TabComponent);
    expect(tabview__TabGroupComponent)
      .withContext('tabview#TabGroupComponent')
      .toBe(canonical__tabs_tab_group_component__TabGroupComponent);
  });

  it('@ciag/orchestra/text re-exports the canonical declarations', () => {
    expect(text__TextComponent)
      .withContext('text#TextComponent')
      .toBe(canonical__p2_p2_layout_components__TextComponent);
  });

  it('@ciag/orchestra/textarea re-exports the canonical declarations', () => {
    expect(textarea__Textarea)
      .withContext('textarea#Textarea')
      .toBe(canonical__input_textarea_component__TextareaComponent);
  });

  // tieredmenu.PrimeMenuItem === ./internal/menu-item#PrimeMenuItem (type-only, checked at generation time)

  it('@ciag/orchestra/tieredmenu re-exports the canonical declarations', () => {
    expect(tieredmenu__TieredMenuComponent)
      .withContext('tieredmenu#TieredMenuComponent')
      .toBe(canonical__tiered_menu_tiered_menu_component__TieredMenuComponent);
  });

  it('@ciag/orchestra/toggle-switch re-exports the canonical declarations', () => {
    expect(toggle_switch__ToggleSwitch)
      .withContext('toggle-switch#ToggleSwitch')
      .toBe(canonical__switch_switch_component__SwitchComponent);
    expect(toggle_switch__ToggleSwitchComponent)
      .withContext('toggle-switch#ToggleSwitchComponent')
      .toBe(canonical__switch_switch_component__SwitchComponent);
  });

  it('@ciag/orchestra/togglebutton re-exports the canonical declarations', () => {
    expect(togglebutton__ToggleButtonComponent)
      .withContext('togglebutton#ToggleButtonComponent')
      .toBe(
        canonical__toggle_button_toggle_button_component__ToggleButtonComponent,
      );
  });

  it('@ciag/orchestra/toggleswitch re-exports the canonical declarations', () => {
    expect(toggleswitch__ToggleSwitch)
      .withContext('toggleswitch#ToggleSwitch')
      .toBe(canonical__switch_switch_component__SwitchComponent);
    expect(toggleswitch__ToggleSwitchComponent)
      .withContext('toggleswitch#ToggleSwitchComponent')
      .toBe(canonical__switch_switch_component__SwitchComponent);
  });

  // treeselect.TreeSelectNode === ./tree-select/tree-select.component#TreeSelectNode (type-only, checked at generation time)

  it('@ciag/orchestra/treeselect re-exports the canonical declarations', () => {
    expect(treeselect__TreeSelectComponent)
      .withContext('treeselect#TreeSelectComponent')
      .toBe(canonical__tree_select_tree_select_component__TreeSelectComponent);
  });

  // treetable.HierarchyNode === ./tree/tree.component#HierarchyNode (type-only, checked at generation time)

  // treetable.TreeTableColumn === ./tree-table/tree-table.component#TreeTableColumn (type-only, checked at generation time)

  // treetable.TreeTableSortEvent === ./tree-table/tree-table.component#TreeTableSortEvent (type-only, checked at generation time)

  it('@ciag/orchestra/treetable re-exports the canonical declarations', () => {
    expect(treetable__TreeTableComponent)
      .withContext('treetable#TreeTableComponent')
      .toBe(canonical__tree_table_tree_table_component__TreeTableComponent);
  });

  it('@ciag/orchestra/typography re-exports the canonical declarations', () => {
    expect(typography__TypographyComponent)
      .withContext('typography#TypographyComponent')
      .toBe(canonical__p2_p2_layout_components__TypographyComponent);
  });

  it('@ciag/orchestra/use-style re-exports the canonical declarations', () => {
    expect(use_style__UseStyleDirective)
      .withContext('use-style#UseStyleDirective')
      .toBe(canonical__p2_p2_utility_more__UseStyleDirective);
  });

  it('@ciag/orchestra/usestyle re-exports the canonical declarations', () => {
    expect(usestyle__UseStyleDirective)
      .withContext('usestyle#UseStyleDirective')
      .toBe(canonical__p2_p2_utility_more__UseStyleDirective);
  });

  it('@ciag/orchestra/visually-hidden re-exports the canonical declarations', () => {
    expect(visually_hidden__VisuallyHiddenComponent)
      .withContext('visually-hidden#VisuallyHiddenComponent')
      .toBe(canonical__p2_p2_layout_components__VisuallyHiddenComponent);
  });
});
