import { AfterViewInit, booleanAttribute, ChangeDetectionStrategy, Component, ElementRef, forwardRef, input, model, output, signal, viewChild } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { P2_SHARED_STYLES } from './p2-shared';

export type ChartType = 'bar' | 'line' | 'doughnut';
export interface ChartDataset { label?: string; data: number[]; backgroundColor?: string | string[]; borderColor?: string; }
export interface ChartData { labels: string[]; datasets: ChartDataset[]; }
export interface EditorAction { command: string; icon?: string; label?: string; }

@Component({
  selector: 'orc-chart', standalone: true,
  template: `<div class="orc-chart" [class]="styleClass()" [style.width]="width()" [style.height]="height()" [attr.aria-label]="ariaLabel()" [attr.aria-labelledby]="ariaLabelledBy()"><svg #chartSvg viewBox="0 0 100 60" preserveAspectRatio="none" role="img"><g class="grid"><line x1="5" y1="5" x2="5" y2="55" /><line x1="5" y1="55" x2="98" y2="55" /></g>@if (type() === 'bar') { @for (bar of bars(); track $index) { <rect [attr.x]="bar.x" [attr.y]="bar.y" [attr.width]="bar.width" [attr.height]="bar.height" [attr.fill]="bar.color" (click)="selectPoint(bar.index, $event)" /> } } @else if (type() === 'line') { @for (line of lines(); track $index) { <polyline [attr.points]="line.points" [attr.stroke]="line.color" /> @for (point of line.pointList; track $index) { <circle [attr.cx]="point.x" [attr.cy]="point.y" r=".8" [attr.fill]="line.color" (click)="selectPoint(point.index, $event)" /> } } } @else { @for (slice of doughnutSlices(); track $index) { <path [attr.d]="slice.path" [attr.fill]="slice.color" (click)="selectPoint(slice.index, $event)" /> } } </svg><div class="legend">@for (item of legend(); track $index) { <span><i [style.background]="item.color"></i>{{ item.label }}</span> }</div></div>`,
  styles: [P2_SHARED_STYLES + `.orc-chart{display:block;width:100%;min-height:12rem}.orc-chart svg{display:block;width:100%;height:calc(100% - 1.5rem);overflow:visible}.grid line{stroke:var(--orc-component-border);stroke-width:.25}.orc-chart rect{cursor:pointer}.orc-chart polyline{fill:none;stroke-width:1.2;stroke-linejoin:round;stroke-linecap:round}.orc-chart circle{cursor:pointer}.legend{display:flex;flex-wrap:wrap;gap:.7rem;font-size:.75rem;color:var(--orc-component-text-secondary)}.legend span{display:inline-flex;gap:.3rem;align-items:center}.legend i{display:inline-block;width:.65rem;height:.65rem;border-radius:.15rem}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChartComponent {
  readonly type = input<ChartType | 'scatter' | 'bubble' | 'pie' | 'polarArea' | 'radar'>('bar'); readonly data = input<ChartData>({ labels: [], datasets: [] }); readonly plugins = input<any[]>([]); readonly width = input<string | undefined>(undefined); readonly height = input('260px'); readonly responsive = input(true, { transform: booleanAttribute }); readonly styleClass = input(''); readonly ariaLabel = input<string | undefined>(undefined); readonly ariaLabelledBy = input<string | undefined>(undefined); readonly pointClick = output<number>(); readonly onDataSelect = output<{ index: number; originalEvent?: Event }>();
  readonly chartSvg = viewChild<ElementRef<SVGSVGElement>>('chartSvg'); readonly renderVersion = signal(0);
  refresh(): void { this.renderVersion.update(value => value + 1); }
  reinit(): void { this.refresh(); }
  getBase64Image(): string | undefined { const svg = this.chartSvg()?.nativeElement; if (!svg || typeof XMLSerializer === 'undefined') return undefined; const encoded = btoa(unescape(encodeURIComponent(new XMLSerializer().serializeToString(svg)))); return `data:image/svg+xml;base64,${encoded}`; }
  generateLegend(): string { return this.data().labels.join(', '); }
  selectPoint(index: number, event?: Event): void { this.pointClick.emit(index); this.onDataSelect.emit({ index, originalEvent: event }); }
  private color(index: number, dataset: ChartDataset): string { const value = dataset.backgroundColor; return Array.isArray(value) ? (value[index] || '#3b82f6') : (value || '#3b82f6'); }
  private maxValue(): number { return Math.max(1, ...this.data().datasets.flatMap(dataset => dataset.data)); }
  bars(): Array<{ x: number; y: number; width: number; height: number; color: string; index: number }> { const datasets = this.data().datasets; const count = this.data().labels.length; const max = this.maxValue(); const slot = 88 / Math.max(1, count); const width = Math.max(1, slot / Math.max(1, datasets.length) - .8); const result: Array<{ x: number; y: number; width: number; height: number; color: string; index: number }> = []; datasets.forEach((dataset, datasetIndex) => dataset.data.forEach((value, index) => { const height = value / max * 48; result.push({ x: 6 + index * slot + datasetIndex * (width + .4), y: 54 - height, width, height, color: this.color(index, dataset), index }); })); return result; }
  lines(): Array<{ points: string; color: string; pointList: Array<{ x: number; y: number; index: number }> }> { const count = this.data().labels.length; const max = this.maxValue(); return this.data().datasets.map(dataset => { const pointList = dataset.data.map((value, index) => ({ x: 6 + (index * 88 / Math.max(1, count - 1)), y: 54 - value / max * 48, index })); return { points: pointList.map(point => `${point.x},${point.y}`).join(' '), color: dataset.borderColor || this.color(0, dataset), pointList }; }); }
  doughnutSlices(): Array<{ path: string; color: string; index: number }> { const values = this.data().datasets[0]?.data || []; const total = values.reduce((sum, value) => sum + Math.max(0, value), 0) || 1; let start = -Math.PI / 2; return values.map((value, index) => { const end = start + Math.max(0, value) / total * Math.PI * 2; const large = end - start > Math.PI ? 1 : 0; const x1 = 50 + 20 * Math.cos(start); const y1 = 30 + 20 * Math.sin(start); const x2 = 50 + 20 * Math.cos(end); const y2 = 30 + 20 * Math.sin(end); const path = `M 50 30 L ${x1} ${y1} A 20 20 0 ${large} 1 ${x2} ${y2} Z`; start = end; return { path, color: this.color(index, this.data().datasets[0] || { data: [] }), index }; }); }
  legend(): Array<{ label: string; color: string }> { const dataset = this.data().datasets[0]; return this.data().labels.map((label, index) => ({ label, color: this.color(index, dataset || { data: [] }) })); }
}

@Component({
  selector: 'orc-editor', standalone: true,
  template: `<section class="orc-editor" [class]="styleClass()" [class.readonly]="readonly() || cvaDisabled()" [attr.aria-label]="ariaLabel() || null"><div class="toolbar" role="toolbar">@for (action of actions(); track action.command) { <button type="button" [disabled]="readonly() || cvaDisabled()" (click)="exec(action.command)" [attr.aria-label]="action.label || null">{{ action.icon }}</button> }</div><div #surface class="surface" [attr.contenteditable]="readonly() || cvaDisabled() ? 'false' : 'true'" [attr.data-placeholder]="placeholder() || null" [innerHTML]="value()" (input)="onInput($event)" (keyup)="emitSelectionChange($event)" (mouseup)="emitSelectionChange($event)" (blur)="handleBlur()"></div></section>`,
  styles: [P2_SHARED_STYLES + `.orc-editor{width:100%;border:1px solid var(--orc-component-border-strong);border-radius:.5rem;overflow:hidden;background:var(--orc-component-surface)}.toolbar{display:flex;gap:.2rem;padding:.35rem;border-bottom:1px solid var(--orc-component-border);background:var(--orc-component-surface-subtle)}.toolbar button{width:2rem;height:2rem;border:0;border-radius:.3rem;background:transparent}.toolbar button:hover:not(:disabled){background:var(--orc-component-surface-subtle)}.surface{min-height:10rem;padding:.75rem;outline:0;color:var(--orc-component-text)}.surface:empty:before{content:attr(data-placeholder);color:var(--orc-component-text-muted)}.readonly .toolbar{display:none}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => EditorComponent), multi: true }],
})
export class EditorComponent implements ControlValueAccessor, AfterViewInit {
  readonly value = model(''); readonly placeholder = input<string | undefined>(undefined); readonly readonly = input(false, { transform: booleanAttribute }); readonly styleClass = input(''); readonly formats = input<string[] | undefined>(undefined); readonly modules = input<Record<string, unknown> | undefined>(undefined); readonly bounds = input<HTMLElement | string | undefined>(undefined); readonly scrollingContainer = input<HTMLElement | string | undefined>(undefined); readonly debug = input<string | undefined>(undefined); readonly ariaLabel = input<string | undefined>(undefined); readonly actions = input<EditorAction[]>([]); readonly blur = output<string>(); readonly onInit = output<unknown>(); readonly onTextChange = output<{ html: string; text: string; delta?: unknown; source?: string; editor?: unknown }>(); readonly onSelectionChange = output<{ range: { index: number; length: number } | null; oldRange?: { index: number; length: number } | null; source?: string }>();
  readonly editorSurface = viewChild<ElementRef<HTMLElement>>('surface');
  private onModelChange: (value: string) => void = () => {};
  private onModelTouched: () => void = () => {};
  readonly cvaDisabled = signal(false);
  writeValue(value: unknown): void { this.value.set(value == null ? '' : String(value)); }
  registerOnChange(fn: (value: string) => void): void { this.onModelChange = fn; }
  registerOnTouched(fn: () => void): void { this.onModelTouched = fn; }
  setDisabledState(disabled: boolean): void { this.cvaDisabled.set(disabled); }
  onInput(event: Event): void { if (this.readonly() || this.cvaDisabled()) return; const html = (event.target as HTMLElement).innerHTML; const text = (event.target as HTMLElement).innerText; this.value.set(html); this.onModelChange(html); this.onTextChange.emit({ html, text, source: 'user', editor: this.getQuill() }); }
  handleBlur(): void { this.onModelTouched(); this.blur.emit(this.value()); }
  exec(command: string): void { if (this.readonly() || this.cvaDisabled()) return; if (typeof document !== 'undefined') document.execCommand(command); }
  emitSelectionChange(_event: Event): void { if (typeof window === 'undefined') return; const selection = window.getSelection(); const range = selection?.rangeCount ? { index: selection.getRangeAt(0).startOffset, length: selection.toString().length } : null; this.onSelectionChange.emit({ range, oldRange: null, source: 'user' }); }
  ngAfterViewInit(): void { this.onInit.emit({ editor: this.getQuill() }); }
  getQuill(): { root: HTMLElement; getText: () => string; getHTML: () => string; getLength: () => number; format: (name: string, value: unknown) => void; insertText: (index: number, text: string) => void; getSelection: () => { index: number; length: number } | null; setSelection: (index: number, length?: number) => void } | null {
    const root = this.editorSurface()?.nativeElement; if (!root) return null;
    return { root, getText: () => root.innerText, getHTML: () => root.innerHTML, getLength: () => root.innerText.length, format: (name, value) => { if (!this.readonly() && !this.cvaDisabled() && typeof document !== 'undefined') { document.execCommand(name, false, String(value)); } }, insertText: (index, text) => { if (this.readonly() || this.cvaDisabled()) return; const content = root.innerText; root.innerText = content.slice(0, index) + text + content.slice(index); this.onInput({ target: root } as unknown as Event); }, getSelection: () => { const selection = typeof window !== 'undefined' ? window.getSelection() : null; return selection?.rangeCount ? { index: selection.getRangeAt(0).startOffset, length: selection.toString().length } : null; }, setSelection: (index, length = 0) => { if (typeof window === 'undefined') return; const selection = window.getSelection(); const range = document.createRange(); range.setStart(root.firstChild || root, Math.min(index, root.textContent?.length || 0)); range.setEnd(root.firstChild || root, Math.min(index + length, root.textContent?.length || 0)); selection?.removeAllRanges(); selection?.addRange(range); } };
  }
}
