import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { P2Option, P2_SHARED_STYLES } from './p2-shared';

export interface DockItem extends P2Option<string> { command?: () => void; }
@Component({ selector: 'orc-dock', standalone: true, template: `<nav class="orc-dock" [class.top]="position() === 'top'" [class.bottom]="position() === 'bottom'" [attr.aria-label]="label()" role="toolbar">@for (item of items(); track item.value) { <button type="button" [disabled]="item.disabled" [attr.aria-label]="item.label" (click)="item.command?.()"><span>{{ item.icon || '•' }}</span><small>{{ item.label }}</small></button> }</nav>`, styles: [P2_SHARED_STYLES + `.orc-dock{position:fixed;z-index:20;left:50%;display:flex;gap:.4rem;transform:translateX(-50%);padding:.5rem;border:1px solid #e2e8f0;border-radius:.7rem;background:#fff;box-shadow:0 10px 25px #0f172a26}.orc-dock.top{top:1rem}.orc-dock.bottom{bottom:1rem}.orc-dock button{display:grid;justify-items:center;gap:.15rem;min-width:3rem;border:0;border-radius:.45rem;background:transparent;padding:.35rem}.orc-dock button:hover:not(:disabled){background:#eff6ff;color:#2563eb}.orc-dock span{font-size:1.3rem}.orc-dock small{font-size:.65rem}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class DockComponent { readonly items = input<DockItem[]>([]); readonly position = input<'top' | 'bottom'>('bottom'); readonly label = input('Dock'); }

@Component({ selector: 'orc-scroll-panel', standalone: true, template: `<div class="orc-scroll-panel" [style.height]="height()" [style.max-height]="maxHeight()" [attr.aria-label]="label()"><ng-content /></div>`, styles: [P2_SHARED_STYLES + `.orc-scroll-panel{display:block;width:100%;overflow:auto;scrollbar-color:#94a3b8 #f1f5f9;scroll-behavior:smooth}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class ScrollPanelComponent { readonly height = input('auto'); readonly maxHeight = input('20rem'); readonly label = input('Scrollable content'); }
