import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, model, output, signal } from '@angular/core';
import { P2_SHARED_STYLES } from './p2-shared';

export interface HierarchyNode<T = Record<string, unknown>> {
  key: string;
  label: string;
  data?: T;
  children?: HierarchyNode<T>[];
  leaf?: boolean;
  disabled?: boolean;
}
interface FlatHierarchyNode<T> { node: HierarchyNode<T>; level: number; }

@Component({
  selector: 'orc-tree', standalone: true,
  template: `<div class="orc-tree" [class]="styleClass()" role="tree" [attr.aria-label]="label()" [attr.aria-labelledby]="ariaLabelledBy()" [attr.aria-busy]="loading()">@if (loading()) { <span class="loading">Loading</span> }@if (filter()) { <input [value]="filterValue()" [placeholder]="filterPlaceholder()" (input)="onFilterInput($event)" aria-label="Filter tree" /> }@for (item of filteredVisibleNodes(); track item.node.key) { <div class="tree-row" role="treeitem" [attr.aria-level]="item.level" [attr.aria-expanded]="item.node.children?.length ? expanded().has(item.node.key) : null" [class.selected]="isSelected(item.node.key)" [class.disabled]="item.node.disabled" [style.padding-left.rem]=".5 + item.level * 1.1"><button type="button" class="toggle" [disabled]="!item.node.children?.length" (click)="toggle(item.node)">{{ item.node.children?.length ? (expanded().has(item.node.key) ? '▾' : '▸') : '·' }}</button><button type="button" class="label" [disabled]="item.node.disabled" (click)="select(item.node, $event)">{{ item.node.label }}</button></div> } @empty { <span>{{ emptyText() }}</span> }</div>`,
  styles: [P2_SHARED_STYLES + `.orc-tree{width:100%;border:1px solid #e2e8f0;border-radius:.5rem;background:#fff;color:#0f172a}.tree-row{display:flex;align-items:center;min-height:2.25rem}.tree-row.selected{background:#eff6ff}.tree-row.disabled{opacity:.55}.toggle,.label{border:0;background:transparent}.toggle{width:1.5rem}.label{flex:1;padding:.4rem;text-align:left}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeComponent<T = Record<string, unknown>> {
  readonly nodes = input<HierarchyNode<T>[]>([]); readonly label = input('Tree'); readonly ariaLabelledBy = input<string | undefined>(undefined); readonly selectionMode = input<'single' | 'multiple' | 'checkbox'>('single'); readonly metaKeySelection = input(true, { transform: booleanAttribute }); readonly filter = input(false, { transform: booleanAttribute }); readonly filterPlaceholder = input('Filter'); readonly filterValue = model(''); readonly emptyText = input('No nodes'); readonly loading = input(false, { transform: booleanAttribute }); readonly styleClass = input(''); readonly selected = model<string | string[] | null>(null); readonly expanded = signal<ReadonlySet<string>>(new Set()); readonly nodeSelect = output<HierarchyNode<T>>(); readonly nodeUnselect = output<HierarchyNode<T>>(); readonly nodeExpand = output<HierarchyNode<T>>(); readonly nodeCollapse = output<HierarchyNode<T>>(); readonly selectionChange = output<string | string[] | null>(); readonly onFilter = output<{ originalEvent: Event; filter: string }>();
  readonly visibleNodes = computed<FlatHierarchyNode<T>[]>(() => { const result: FlatHierarchyNode<T>[] = []; const visit = (nodes: HierarchyNode<T>[], level: number): void => { for (const node of nodes) { result.push({ node, level }); if (node.children?.length && this.expanded().has(node.key)) visit(node.children, level + 1); } }; visit(this.nodes(), 1); return result; });
  readonly filteredVisibleNodes = computed(() => { const term = this.filterValue().trim().toLowerCase(); return term ? this.visibleNodes().filter(item => item.node.label.toLowerCase().includes(term)) : this.visibleNodes(); });
  toggle(node: HierarchyNode<T>): void { if (!node.children?.length) return; this.expanded.update(current => { const next = new Set(current); const wasOpen = next.has(node.key); wasOpen ? next.delete(node.key) : next.add(node.key); wasOpen ? this.nodeCollapse.emit(node) : this.nodeExpand.emit(node); return next; }); }
  isSelected(key: string): boolean { const selected = this.selected(); return Array.isArray(selected) ? selected.includes(key) : selected === key; }
  select(node: HierarchyNode<T>, event?: Event): void { if (node.disabled) return; const current = this.selected(); let next: string | string[] | null; if (this.selectionMode() === 'single') next = current === node.key ? null : node.key; else { const values = Array.isArray(current) ? [...current] : current ? [current] : []; const index = values.indexOf(node.key); index >= 0 ? values.splice(index, 1) : values.push(node.key); next = values; } this.selected.set(next); this.selectionChange.emit(next); this.isSelected(node.key) ? this.nodeSelect.emit(node) : this.nodeUnselect.emit(node); }
  onFilterInput(event: Event): void { const filter = (event.target as HTMLInputElement).value; this.filterValue.set(filter); this.onFilter.emit({ originalEvent: event, filter }); }
}

export interface TreeTableColumn { key: string; header: string; }
@Component({
  selector: 'orc-tree-table', standalone: true,
  template: `<div class="orc-tree-table" [class]="styleClass()" [attr.aria-label]="label()" [attr.aria-labelledby]="ariaLabelledBy()" [attr.aria-busy]="loading()"><table><thead><tr><th scope="col">{{ treeColumnHeader() }}</th>@for (column of columns(); track column.key) { <th scope="col">{{ column.header }}</th> }</tr></thead><tbody>@for (item of visibleNodes(); track item.node.key) { <tr [class.selected]="selected().has(item.node.key)" [style.background]="selected().has(item.node.key) ? '#eff6ff' : null"><td [style.padding-left.rem]=".5 + item.level * 1.1"><button type="button" class="toggle" [disabled]="!item.node.children?.length" (click)="toggle(item)">{{ item.node.children?.length ? (expanded().has(item.node.key) ? '▾' : '▸') : '·' }}</button><input type="checkbox" [checked]="selected().has(item.node.key)" [disabled]="item.node.disabled" (change)="select(item, ($any($event.target)).checked)" /><span>{{ item.node.label }}</span></td>@for (column of columns(); track column.key) { <td>{{ cellValue(item.node, column.key) }}</td> }</tr> } @empty { <tr><td [attr.colspan]="columns().length + 1">{{ emptyText() }}</td></tr> }</tbody></table></div>`,
  styles: [P2_SHARED_STYLES + `.orc-tree-table{width:100%;overflow:auto;border:1px solid #e2e8f0;border-radius:.5rem;background:#fff}.orc-tree-table table{width:100%;border-collapse:collapse;color:#0f172a}.orc-tree-table th,.orc-tree-table td{padding:.65rem .75rem;border-bottom:1px solid #e2e8f0;text-align:left}.orc-tree-table th{background:#f8fafc}.toggle{width:1.5rem;border:0;background:transparent}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeTableComponent<T = Record<string, unknown>> {
  readonly value = input<HierarchyNode<T>[]>([]); readonly columns = input<TreeTableColumn[]>([]); readonly label = input('Tree table'); readonly ariaLabelledBy = input<string | undefined>(undefined); readonly treeColumnHeader = input('Name'); readonly emptyText = input('No data'); readonly loading = input(false, { transform: booleanAttribute }); readonly styleClass = input(''); readonly expanded = signal<ReadonlySet<string>>(new Set()); readonly selected = model<ReadonlySet<string>>(new Set()); readonly nodeSelect = output<HierarchyNode<T>>(); readonly nodeUnselect = output<HierarchyNode<T>>(); readonly nodeExpand = output<HierarchyNode<T>>(); readonly nodeCollapse = output<HierarchyNode<T>>(); readonly selectionChange = output<ReadonlySet<string>>(); readonly rowExpand = output<HierarchyNode<T>>(); readonly rowCollapse = output<HierarchyNode<T>>();
  readonly visibleNodes = computed<FlatHierarchyNode<T>[]>(() => { const result: FlatHierarchyNode<T>[] = []; const visit = (nodes: HierarchyNode<T>[], level: number): void => { for (const node of nodes) { result.push({ node, level }); if (node.children?.length && this.expanded().has(node.key)) visit(node.children, level + 1); } }; visit(this.value(), 1); return result; });
  toggle(item: FlatHierarchyNode<T>): void { const node = item.node; if (!node.children?.length) return; this.expanded.update(current => { const next = new Set(current); const open = next.has(node.key); open ? next.delete(node.key) : next.add(node.key); (open ? this.nodeCollapse : this.nodeExpand).emit(node); (open ? this.rowCollapse : this.rowExpand).emit(node); return next; }); }
  select(item: FlatHierarchyNode<T>, checked: boolean): void { if (item.node.disabled) return; const next = new Set(this.selected()); checked ? next.add(item.node.key) : next.delete(item.node.key); this.selected.set(next); this.selectionChange.emit(next); (checked ? this.nodeSelect : this.nodeUnselect).emit(item.node); }
  cellValue(node: HierarchyNode<T>, key: string): unknown { return node.data && typeof node.data === 'object' ? (node.data as Record<string, unknown>)[key] ?? '' : ''; }
}
