import { ChangeDetectionStrategy, Component, input, model, output } from '@angular/core';
import { P2_SHARED_STYLES } from './p2-shared';

@Component({ selector: 'orc-input-group-addon', standalone: true, template: `<span class="orc-input-addon"><ng-content /></span>`, styles: [P2_SHARED_STYLES + `.orc-input-addon{display:inline-flex;align-items:center;min-height:2.5rem;padding:0 .7rem;border:1px solid #cbd5e1;background:#f8fafc;color:#475569}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class InputGroupAddonComponent {}

@Component({ selector: 'orc-icon-field', standalone: true, template: `<span class="orc-icon-field"><span class="icon" aria-hidden="true">{{ icon() }}</span><ng-content /></span>`, styles: [P2_SHARED_STYLES + `.orc-icon-field{position:relative;display:inline-flex;align-items:center;width:100%}.orc-icon-field .icon{position:absolute;left:.7rem;z-index:1;color:#64748b}.orc-icon-field ::ng-deep input{padding-left:2rem}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class IconFieldComponent { readonly icon = input('⌕'); }

@Component({ selector: 'orc-ifta-label', standalone: true, template: `<span class="orc-ifta"><ng-content /></span>`, styles: [P2_SHARED_STYLES + `.orc-ifta{position:relative;display:block;padding-top:.75rem}.orc-ifta>label{position:absolute;top:0;left:.65rem;padding:0 .2rem;background:#fff;color:#64748b;font-size:.75rem}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class IftaLabelComponent {}

@Component({ selector: 'orc-inplace', standalone: true, template: `@if (!active()) { <button type="button" class="display" (click)="activate()"><ng-content select="[orcInplaceDisplay]" />{{ label() }}</button> } @else { <div class="content"><ng-content select="[orcInplaceContent]" /><ng-content /><button type="button" class="close" (click)="deactivate()" [attr.aria-label]="closeLabel()">×</button></div> }`, styles: [P2_SHARED_STYLES + `.display{border:0;background:transparent;padding:.35rem;color:#2563eb;text-decoration:underline}.content{position:relative;display:flex;align-items:center;gap:.5rem}.close{border:0;background:transparent}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class InplaceComponent { readonly active = model(false); readonly label = input('Edit'); readonly closeLabel = input('Close'); readonly activated = output<void>(); readonly deactivated = output<void>(); activate(): void { this.active.set(true); this.activated.emit(); } deactivate(): void { this.active.set(false); this.deactivated.emit(); } }

@Component({ selector: 'orc-terminal', standalone: true, template: `<section class="orc-terminal" [attr.aria-label]="ariaLabel()"><div class="history">@for (line of history(); track $index) { <div><span class="prompt">{{ prompt() }}</span>{{ line.command }} @if (line.output) { <pre>{{ line.output }}</pre> }</div> }</div><form (submit)="submit($event)"><span class="prompt">{{ prompt() }}</span><input [value]="command()" (input)="command.set(($any($event.target)).value)" autocomplete="off" [attr.aria-label]="'Terminal command'" /></form></section>`, styles: [P2_SHARED_STYLES + `.orc-terminal{display:block;padding:.8rem;border-radius:.6rem;background:#0f172a;color:#e2e8f0;font: .85rem/1.5 ui-monospace,monospace}.history{max-height:18rem;overflow:auto}.prompt{color:#4ade80}.history pre{margin:.15rem 0 .5rem;white-space:pre-wrap;color:#cbd5e1}.orc-terminal form{display:flex;gap:.3rem}.orc-terminal input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:inherit;font:inherit}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class TerminalComponent { readonly prompt = input('$ '); readonly ariaLabel = input('Terminal'); readonly command = model(''); readonly history = model<TerminalLine[]>([]); readonly commandRun = output<string>(); submit(event: Event): void { event.preventDefault(); const value = this.command().trim(); if (!value) return; this.history.update(lines => [...lines, { command: value }]); this.command.set(''); this.commandRun.emit(value); } }
export interface TerminalLine { command: string; output?: string; }

@Component({ selector: 'orc-image-compare', standalone: true, template: `<div class="orc-image-compare" [style.aspect-ratio]="aspectRatio()"><img class="after" [src]="after()" [alt]="afterAlt()" /><div class="before" [style.width.%]="position()"><img [src]="before()" [alt]="beforeAlt()" /></div><input type="range" min="0" max="100" [value]="position()" (input)="position.set(+$any($event.target).value)" aria-label="Compare images" /></div>`, styles: [P2_SHARED_STYLES + `.orc-image-compare{position:relative;overflow:hidden;width:100%;background:#e2e8f0}.orc-image-compare img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.orc-image-compare .before{position:absolute;inset:0;overflow:hidden;border-right:2px solid #fff}.orc-image-compare input{position:absolute;inset:auto 0 .5rem;width:calc(100% - 1rem);margin:auto}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class ImageCompareComponent { readonly before = input(''); readonly after = input(''); readonly beforeAlt = input('Before'); readonly afterAlt = input('After'); readonly aspectRatio = input('16 / 9'); readonly position = model(50); }
