import { booleanAttribute, ChangeDetectionStrategy, Component, computed, effect, input, model, output, OnDestroy } from '@angular/core';
import { P2Option, P2_SHARED_STYLES } from './p2-shared';

@Component({
  selector: 'orc-order-list', standalone: true,
  template: `<section class="p-orderlist p-component orc-order-list" [class]="'p-orderlist p-component orc-order-list ' + styleClass()" [style]="style()" [attr.aria-label]="label()" [attr.aria-labelledby]="ariaLabelledBy()" [attr.aria-disabled]="disabled()" [attr.tabindex]="tabindex()" [attr.data-pc-name]="'orderlist'" (focus)="onFocus.emit($event)" (blur)="onBlur.emit($event)"><header>{{ header() }}<span><button type="button" [disabled]="disabled() || !canMove(-1)" (click)="move(-1)" aria-label="Move up">↑</button><button type="button" [disabled]="disabled() || !canMove(1)" (click)="move(1)" aria-label="Move down">↓</button></span></header>@if (filterBy()) { <input [value]="filter()" [placeholder]="filterPlaceholder()" [attr.aria-label]="ariaFilterLabel()" (input)="setFilter($any($event.target).value)" /> }<ol role="listbox" [attr.aria-multiselectable]="selectionMode() === 'multiple'">@for (item of filteredValue(); track $index) { <li role="option" [attr.aria-selected]="selectedItems().has(item)" [class.selected]="selectedItems().has(item)" (click)="select(value().indexOf(item))">{{ itemLabel(item) }}</li> } @empty { <li class="empty">{{ emptyText() }}</li> }</ol></section>`,
  styles: [P2_SHARED_STYLES + `.orc-order-list{border:1px solid #e2e8f0;border-radius:.5rem;overflow:hidden;background:#fff}.orc-order-list header{display:flex;justify-content:space-between;padding:.65rem .8rem;background:#f8fafc;font-weight:700}.orc-order-list header button{margin-left:.2rem;border:1px solid #cbd5e1;border-radius:.3rem;background:#fff}.orc-order-list ol{min-height:8rem;margin:0;padding:.35rem;list-style:none}.orc-order-list li{padding:.55rem .65rem;border-radius:.35rem;cursor:pointer}.orc-order-list li.selected{background:#eff6ff;color:#1d4ed8}.orc-order-list .empty{color:#64748b}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OrderListComponent<T = unknown> {
  readonly value = model<T[]>([]); readonly label = input('Order list'); readonly header = input('Items'); readonly emptyText = input('No items'); readonly style = input<Record<string, any> | null | undefined>(undefined); readonly styleClass = input(''); readonly tabindex = input(0); readonly ariaLabelledBy = input<string | undefined>(undefined); readonly ariaFilterLabel = input('Filter items'); readonly listStyle = input<Record<string, any> | null | undefined>(undefined); readonly filterBy = input<string | undefined>(undefined); readonly filterPlaceholder = input('Filter'); readonly filterLocale = input<string | undefined>(undefined); readonly filter = model(''); readonly dragdrop = input(false, { transform: booleanAttribute }); readonly metaKeySelection = input(true, { transform: booleanAttribute }); readonly disabled = input(false, { transform: booleanAttribute }); readonly selectionMode = input<'single' | 'multiple'>('single'); readonly selectedIndex = model(-1); readonly selected = model<T | T[] | null>(null, { alias: 'selection' }); readonly valueChangeEvent = output<T[]>(); readonly reorder = output<{ value: T[]; direction: 'up' | 'down' }>(); readonly onReorder = this.reorder; readonly onFilterEvent = output<{ filter: string }>(); readonly onFocus = output<Event>(); readonly onBlur = output<Event>();
  readonly filteredValue = computed(() => { const query = this.filter().trim().toLocaleLowerCase(this.filterLocale() || undefined); if (!query) return this.value(); const field = this.filterBy(); return this.value().filter(item => String(field ? (item as any)?.[field] ?? '' : this.itemLabel(item)).toLocaleLowerCase(this.filterLocale() || undefined).includes(query)); });
  readonly selectedItems = computed(() => { const selected = this.selected(); return new Set(Array.isArray(selected) ? selected : selected == null ? [] : [selected]); });
  itemLabel(item: T): string { return item && typeof item === 'object' ? String((item as Record<string, unknown>)['label'] ?? '') : String(item ?? ''); }
  canMove(delta: number): boolean { const index = this.selectedIndex(); return index >= 0 && index < this.value().length && index + delta >= 0 && index + delta < this.value().length; }
  selection(): T | T[] | null { return this.selected(); }
  select(index: number): void { if (this.disabled() || index < 0 || index >= this.value().length) return; this.selectedIndex.set(index); const item = this.value()[index] ?? null; if (this.selectionMode() === 'multiple') { const current = Array.isArray(this.selected()) ? [...this.selected() as T[]] : this.selected() ? [this.selected() as T] : []; const position = current.indexOf(item as T); position >= 0 ? current.splice(position, 1) : current.push(item as T); this.selected.set(current); } else this.selected.set(item); }
  setFilter(value: string): void { this.filter.set(value); this.onFilterEvent.emit({ filter: value }); }
  move(delta: number): void { if (this.disabled() || !this.canMove(delta)) return; const next = [...this.value()]; const index = this.selectedIndex(); [next[index], next[index + delta]] = [next[index + delta], next[index]]; this.value.set(next); this.selectedIndex.set(index + delta); this.valueChangeEvent.emit(next); this.reorder.emit({ value: next, direction: delta < 0 ? 'up' : 'down' }); }
}

@Component({
  selector: 'orc-pick-list', standalone: true,
  template: `<section class="p-picklist p-component orc-pick-list" [class]="'p-picklist p-component orc-pick-list ' + styleClass()" [style]="style()" [attr.aria-label]="label()" [attr.data-pc-name]="'picklist'"><div class="list-pane" [style]="sourceStyle()"><header>{{ sourceHeader() }}</header>@if (filterBy()) { <input [value]="sourceFilter()" [placeholder]="sourceFilterPlaceholder()" [attr.aria-label]="ariaSourceFilterLabel()" (input)="sourceFilter.set($any($event.target).value)" /> }<ul role="listbox">@for (item of filteredSource(); track item.value) { <li role="option" [class.selected]="sourceSelected().has(item.value)" (click)="toggleSource(item)">{{ item.label }}</li> } @empty { <li class="empty">{{ emptyText() }}</li> }</ul></div><div class="actions"><button type="button" (click)="transferSelected()" [disabled]="disabled() || !sourceSelected().size">→</button><button type="button" (click)="transferBack()" [disabled]="disabled() || !targetSelected().size">←</button></div><div class="list-pane" [style]="targetStyle()"><header>{{ targetHeader() }}</header>@if (filterBy()) { <input [value]="targetFilter()" [placeholder]="targetFilterPlaceholder()" [attr.aria-label]="ariaTargetFilterLabel()" (input)="targetFilter.set($any($event.target).value)" /> }<ul role="listbox">@for (item of filteredTarget(); track item.value) { <li role="option" [class.selected]="targetSelected().has(item.value)" (click)="toggleTarget(item)">{{ item.label }}</li> } @empty { <li class="empty">{{ emptyText() }}</li> }</ul></div></section>`,
  styles: [P2_SHARED_STYLES + `.orc-pick-list{display:grid;grid-template-columns:1fr auto 1fr;gap:.7rem;align-items:center}.list-pane{min-width:0;border:1px solid #e2e8f0;border-radius:.5rem;overflow:hidden;background:#fff}.list-pane header{padding:.6rem .75rem;background:#f8fafc;font-weight:700}.list-pane ul{min-height:10rem;max-height:16rem;overflow:auto;margin:0;padding:.35rem;list-style:none}.list-pane li{padding:.5rem .6rem;border-radius:.35rem;cursor:pointer}.list-pane li.selected{background:#eff6ff;color:#1d4ed8}.actions{display:grid;gap:.4rem}.actions button{border:1px solid #cbd5e1;border-radius:.35rem;background:#fff;padding:.45rem}.empty{color:#64748b}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PickListComponent<T extends P2Option = P2Option> {
  readonly source = model<T[]>([]); readonly target = model<T[]>([]); readonly label = input('Pick list'); readonly sourceHeader = input('Available'); readonly targetHeader = input('Selected'); readonly emptyText = input('No items'); readonly style = input<Record<string, any> | null | undefined>(undefined); readonly styleClass = input(''); readonly responsive = input(false, { transform: booleanAttribute }); readonly filterBy = input<string | undefined>(undefined); readonly filterLocale = input<string | undefined>(undefined); readonly filterMatchMode = input('contains'); readonly sourceFilter = model(''); readonly targetFilter = model(''); readonly sourceFilterPlaceholder = input('Filter'); readonly targetFilterPlaceholder = input('Filter'); readonly ariaSourceFilterLabel = input('Filter available items'); readonly ariaTargetFilterLabel = input('Filter selected items'); readonly sourceStyle = input<Record<string, any> | null | undefined>(undefined); readonly targetStyle = input<Record<string, any> | null | undefined>(undefined); readonly dragdrop = input(false, { transform: booleanAttribute }); readonly metaKeySelection = input(true, { transform: booleanAttribute }); readonly stripedRows = input(false, { transform: booleanAttribute }); readonly keepSelection = input(false, { transform: booleanAttribute }); readonly breakpoint = input('960px'); readonly disabled = input(false, { transform: booleanAttribute }); readonly sourceSelected = model<ReadonlySet<T['value']>>(new Set()); readonly targetSelected = model<ReadonlySet<T['value']>>(new Set()); readonly transfer = output<{ source: T[]; target: T[] }>(); readonly selectionChange = output<{ source: ReadonlySet<T['value']>; target: ReadonlySet<T['value']> }>(); readonly onMoveToTarget = output<{ items: T[]; source: T[]; target: T[] }>(); readonly onMoveToSource = output<{ items: T[]; source: T[]; target: T[] }>(); readonly onMoveAllToTarget = this.onMoveToTarget; readonly onMoveAllToSource = this.onMoveToSource; readonly onSourceReorder = output<{ value: T[] }>(); readonly onTargetReorder = output<{ value: T[] }>();
  readonly filteredSource = computed(() => this.filterItems(this.source(), this.sourceFilter()));
  readonly filteredTarget = computed(() => this.filterItems(this.target(), this.targetFilter()));
  private filterItems(items: T[], query: string): T[] { const term = query.trim().toLocaleLowerCase(this.filterLocale() || undefined); if (!term) return items; const field = this.filterBy(); return items.filter(item => String(field ? (item as any)?.[field] ?? '' : item.label ?? '').toLocaleLowerCase(this.filterLocale() || undefined).includes(term)); }
  toggleSource(item: T): void { if (this.disabled()) return; this.sourceSelected.update(current => { const next = new Set(current); next.has(item.value) ? next.delete(item.value) : next.add(item.value); this.selectionChange.emit({ source: next, target: this.targetSelected() }); return next; }); }
  toggleTarget(item: T): void { if (this.disabled()) return; this.targetSelected.update(current => { const next = new Set(current); next.has(item.value) ? next.delete(item.value) : next.add(item.value); this.selectionChange.emit({ source: this.sourceSelected(), target: next }); return next; }); }
  transferSelected(): void { if (this.disabled()) return; const selected = this.sourceSelected(); const moved = this.source().filter(item => selected.has(item.value)); this.source.set(this.source().filter(item => !selected.has(item.value))); this.target.update(items => [...items, ...moved]); this.sourceSelected.set(new Set()); this.emitTransfer(); this.onMoveToTarget.emit({ items: moved, source: this.source(), target: this.target() }); }
  transferBack(): void { if (this.disabled()) return; const selected = this.targetSelected(); const moved = this.target().filter(item => selected.has(item.value)); this.target.set(this.target().filter(item => !selected.has(item.value))); this.source.update(items => [...items, ...moved]); this.targetSelected.set(new Set()); this.emitTransfer(); this.onMoveToSource.emit({ items: moved, source: this.source(), target: this.target() }); }
  private emitTransfer(): void { this.transfer.emit({ source: this.source(), target: this.target() }); }
}

export interface GalleryImage { src: string; alt?: string; thumbnail?: string; title?: string; }
@Component({
  selector: 'orc-galleria, orc-gallery', standalone: true,
  template: `<section class="orc-galleria" [class.orc-galleria--fullscreen]="fullScreen() && visible()" [class]="containerClass()" [style]="containerStyle()" [attr.aria-label]="label()" [attr.aria-roledescription]="'gallery'" tabindex="0" (keydown)="onKeydown($event)">@if (fullScreen() && visible()) { <div class="orc-galleria__mask" [class]="maskClass()" [style.z-index]="baseZIndex()" (click)="hide()"></div> }<div class="orc-galleria__content">@if (fullScreen() && visible()) { <button type="button" class="orc-galleria__close" aria-label="Close" (click)="hide()">×</button> }@if (images()[activeIndex()]; as image) { <figure><img [src]="image.src" [alt]="image.alt || image.title || ''" /><figcaption>{{ image.title }}</figcaption></figure> } @if (showThumbnails()) { <div class="thumbs">@for (image of images(); track $index) { <button type="button" [class.active]="$index === activeIndex()" [attr.aria-label]="'Show image ' + ($index + 1)" (mouseenter)="changeItemOnIndicatorHover() && goTo($index)" (click)="goTo($index)"><img [src]="image.thumbnail || image.src" [alt]="image.alt || ''" /></button> }</div> }<nav>@if (showItemNavigators()) { <button type="button" (click)="previous()" [disabled]="!canPrevious()" aria-label="Previous image">‹</button> }@if (showIndicators()) { <span>{{ images().length ? activeIndex() + 1 : 0 }} / {{ images().length }}</span> }@if (showItemNavigators()) { <button type="button" (click)="next()" [disabled]="!canNext()" aria-label="Next image">›</button> }</nav></div></section>`,
  styles: [P2_SHARED_STYLES + `.orc-galleria{position:relative;display:grid;gap:.5rem;width:100%;max-width:48rem}.orc-galleria__content{position:relative;z-index:1;display:grid;gap:.5rem}.orc-galleria--fullscreen{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;max-width:none;padding:1rem}.orc-galleria__mask{position:absolute;inset:0;background:#000b}.orc-galleria__close{position:absolute;z-index:2;top:.5rem;right:.5rem;border:0;border-radius:50%;background:#0009;color:#fff;font-size:1.5rem;width:2rem;height:2rem}.orc-galleria figure{position:relative;margin:0;aspect-ratio:16/9;overflow:hidden;border-radius:.5rem;background:#f1f5f9}.orc-galleria figure img{width:100%;height:100%;object-fit:contain}.orc-galleria figcaption{position:absolute;right:0;bottom:0;left:0;padding:.45rem .7rem;background:#0f172a99;color:#fff}.thumbs{display:flex;gap:.35rem;overflow:auto}.thumbs button{width:4rem;height:3rem;padding:0;border:2px solid transparent;border-radius:.3rem;overflow:hidden}.thumbs button.active{border-color:#2563eb}.thumbs img{width:100%;height:100%;object-fit:cover}.orc-galleria nav{display:flex;justify-content:center;gap:1rem;align-items:center}.orc-galleria nav button{border:1px solid #cbd5e1;border-radius:.3rem;background:#fff}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GalleriaComponent implements OnDestroy { readonly images = input<GalleryImage[]>([]); readonly label = input('Gallery'); readonly activeIndex = model(0); readonly fullScreen = model(false); readonly visible = model(true); readonly numVisible = input(3); readonly responsiveOptions = input<unknown[] | undefined>(undefined); readonly showItemNavigators = input(true, { transform: booleanAttribute }); readonly showThumbnailNavigators = input(true, { transform: booleanAttribute }); readonly showItemNavigatorsOnHover = input(false, { transform: booleanAttribute }); readonly changeItemOnIndicatorHover = input(false, { transform: booleanAttribute }); readonly shouldStopAutoplayByClick = input(false, { transform: booleanAttribute }); readonly circular = input(false, { transform: booleanAttribute }); readonly autoPlay = input(false, { transform: booleanAttribute }); readonly transitionInterval = input(0); readonly showThumbnails = input(true, { transform: booleanAttribute }); readonly thumbnailsPosition = input<'bottom' | 'top' | 'left' | 'right'>('bottom'); readonly showIndicators = input(true, { transform: booleanAttribute }); readonly showIndicatorsOnItem = input(false, { transform: booleanAttribute }); readonly indicatorsPosition = input<'bottom' | 'top' | 'left' | 'right'>('bottom'); readonly baseZIndex = input(0); readonly maskClass = input(''); readonly containerClass = input(''); readonly containerStyle = input<Record<string, string | number> | undefined>(undefined); readonly showTransitionOptions = input('150ms cubic-bezier(0, 0, 0.2, 1)'); readonly hideTransitionOptions = input('150ms cubic-bezier(0, 0, 0.2, 1)'); readonly imageChange = output<{ index: number; image: GalleryImage }>(); readonly canPrevious = computed(() => this.circular() || this.activeIndex() > 0); readonly canNext = computed(() => this.circular() || this.activeIndex() < this.images().length - 1); private slideshowTimer: ReturnType<typeof setInterval> | null = null;
  constructor() { effect(() => { this.autoPlay(); this.transitionInterval(); this.restartSlideShow(); }); }
  startSlideShow(): void { this.stopSlideShow(); const interval = this.transitionInterval(); if (this.autoPlay() && interval > 0) this.slideshowTimer = setInterval(() => this.next(), interval); }
  stopSlideShow(): void { if (this.slideshowTimer) { clearInterval(this.slideshowTimer); this.slideshowTimer = null; } }
  restartSlideShow(): void { this.startSlideShow(); }
  ngOnDestroy(): void { this.stopSlideShow(); }
  show(): void { this.visible.set(true); }
  hide(): void { this.visible.set(false); }
  toggle(): void { this.visible.update(value => !value); }
  goTo(index: number): void { const image = this.images()[index]; if (!image) return; this.activeIndex.set(index); this.imageChange.emit({ index, image }); if (this.shouldStopAutoplayByClick()) this.stopSlideShow(); } previous(): void { const count = this.images().length; if (!count) return; const index = this.circular() ? (this.activeIndex() - 1 + count) % count : Math.max(0, this.activeIndex() - 1); this.goTo(index); } next(): void { const count = this.images().length; if (!count) return; const index = this.circular() ? (this.activeIndex() + 1) % count : Math.min(count - 1, this.activeIndex() + 1); this.goTo(index); } onKeydown(event: KeyboardEvent): void { if (event.key === 'Escape' && this.fullScreen() && this.visible()) { event.preventDefault(); this.hide(); } else if (event.key === 'ArrowLeft') { event.preventDefault(); this.previous(); } else if (event.key === 'ArrowRight') { event.preventDefault(); this.next(); } else if (event.key === 'Home') { event.preventDefault(); this.goTo(0); } else if (event.key === 'End') { event.preventDefault(); this.goTo(this.images().length - 1); } }
}
