import { booleanAttribute, ChangeDetectionStrategy, Component, computed, forwardRef, input, model, output } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { P2_SHARED_STYLES } from './p2-shared';

export interface OrganizationNode { key: string; label: string; subtitle?: string; image?: string; children?: OrganizationNode[]; disabled?: boolean; }
interface FlatOrganizationNode { node: OrganizationNode; level: number; last: boolean; }

@Component({
  selector: 'orc-organization-chart', standalone: true,
  template: `<section class="orc-org" [attr.aria-label]="label()"><div class="tree">@for (item of flatNodes(); track item.node.key) { <article class="node" [class.disabled]="item.node.disabled" [style.margin-left.rem]="item.level * 2.2"><div class="card" [class.selected]="isSelected(item.node.key)" (click)="select(item.node)">@if (item.node.children?.length) { <button type="button" class="expand" (click)="$event.stopPropagation(); toggle(item.node)" [attr.aria-expanded]="expanded().has(item.node.key)" aria-label="Toggle children">{{ expanded().has(item.node.key) ? '−' : '+' }}</button> } @if (item.node.image) { <img [src]="item.node.image" [alt]="item.node.label" /> }<strong>{{ item.node.label }}</strong>@if (item.node.subtitle) { <small>{{ item.node.subtitle }}</small> }</div></article> }</div></section>`,
  styles: [P2_SHARED_STYLES + `.orc-org{width:100%;overflow:auto}.tree{min-width:18rem;padding:1rem}.node{position:relative;padding:.35rem 0}.node:before{content:'';position:absolute;top:-.35rem;left:-1.1rem;width:1px;height:calc(100% + .35rem);background:var(--orc-component-surface-subtle)}.node:first-child:before{top:50%;height:50%}.card{display:grid;gap:.15rem;width:max-content;min-width:10rem;padding:.65rem .8rem;border:1px solid var(--orc-component-border-strong);border-radius:.5rem;background:var(--orc-component-surface);box-shadow:0 2px 6px var(--orc-component-shadow-color);cursor:pointer}.card:hover{border-color:var(--orc-component-interactive);background:var(--orc-component-interactive-soft)}.card img{width:2rem;height:2rem;border-radius:50%;object-fit:cover}.card small{color:var(--orc-component-text-muted)}.node.disabled{opacity:.5}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OrganizationChartComponent { readonly value = input<OrganizationNode[]>([]); readonly label = input('Organization chart'); readonly selectionMode = input<'single' | 'multiple'>('single'); readonly collapsible = input(true, { transform: booleanAttribute }); readonly selected = model<string | string[] | null>(null); readonly expanded = model<ReadonlySet<string>>(new Set()); readonly nodeSelect = output<OrganizationNode>(); readonly nodeUnselect = output<OrganizationNode>(); readonly nodeExpand = output<OrganizationNode>(); readonly nodeCollapse = output<OrganizationNode>(); readonly selectionChange = output<string | string[] | null>(); readonly flatNodes = computed<FlatOrganizationNode[]>(() => { const result: FlatOrganizationNode[] = []; const visit = (nodes: OrganizationNode[], level: number): void => { nodes.forEach((node, index) => { result.push({ node, level, last: index === nodes.length - 1 }); if (node.children?.length && this.expanded().has(node.key)) visit(node.children, level + 1); }); }; visit(this.value(), 0); return result; }); isSelected(key: string): boolean { const selected = this.selected(); return Array.isArray(selected) ? selected.includes(key) : selected === key; } toggle(node: OrganizationNode): void { if (!this.collapsible() || !node.children?.length || node.disabled) return; const next = new Set(this.expanded()); const open = next.has(node.key); open ? next.delete(node.key) : next.add(node.key); this.expanded.set(next); (open ? this.nodeCollapse : this.nodeExpand).emit(node); } select(node: OrganizationNode): void { if (node.disabled) return; const current = this.selected(); const next = this.selectionMode() === 'single' ? (current === node.key ? null : node.key) : (() => { const values = Array.isArray(current) ? [...current] : current ? [current] : []; const index = values.indexOf(node.key); index >= 0 ? values.splice(index, 1) : values.push(node.key); return values; })(); this.selected.set(next); this.selectionChange.emit(next); (this.isSelected(node.key) ? this.nodeSelect : this.nodeUnselect).emit(node); } }

@Component({
  selector: 'orc-knob', standalone: true,
  template: `<div class="orc-knob" [attr.aria-label]="ariaLabel()"><svg viewBox="0 0 100 100" role="img"><circle class="track" cx="50" cy="50" r="40" [style.stroke-width.px]="strokeWidth()" [style.stroke]="rangeColor()" /><circle class="progress" cx="50" cy="50" r="40" [style.stroke-width.px]="strokeWidth()" [style.stroke]="valueColor()" [style.stroke-dasharray]="circumference" [style.stroke-dashoffset]="dashOffset()" /><text x="50" y="54" text-anchor="middle">{{ valueTemplate() || (value() + suffix()) }}</text></svg><input [id]="inputId()" type="range" [min]="min()" [max]="max()" [step]="step()" [value]="value()" [disabled]="disabled() || cvaDisabled" (input)="onInput($event)" (focus)="onFocus.emit($event)" (blur)="onBlur.emit($event); onModelTouched()" [attr.aria-label]="ariaLabel()" /></div>`,
  styles: [P2_SHARED_STYLES + `.orc-knob{position:relative;display:inline-block;width:8rem;height:8rem}.orc-knob svg{width:100%;height:100%;transform:rotate(-90deg)}.orc-knob circle{fill:none;stroke-width:10}.orc-knob .track{stroke:var(--orc-component-border)}.orc-knob .progress{stroke:var(--orc-component-interactive);stroke-linecap:round;transition:stroke-dashoffset .15s}.orc-knob text{fill:var(--orc-component-text);font-size:1rem;font-weight:700;transform:rotate(90deg);transform-origin:50px 50px}.orc-knob input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:pointer}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => KnobComponent), multi: true }],
})
export class KnobComponent implements ControlValueAccessor { readonly value = model(0); readonly min = input(0); readonly max = input(100); readonly step = input(1); readonly suffix = input(''); readonly disabled = input(false, { transform: booleanAttribute }); readonly readonly = input(false, { transform: booleanAttribute }); readonly ariaLabel = input('Knob'); readonly inputId = input<string | undefined>(undefined); readonly size = input<number | undefined>(undefined); readonly strokeWidth = input(10); readonly valueColor = input('var(--orc-interactive)'); readonly rangeColor = input('var(--orc-border-strong)'); readonly valueTemplate = input<string | undefined>(undefined); readonly valueChangeEvent = output<number>(); readonly onChange = output<number>(); readonly onFocus = output<Event>(); readonly onBlur = output<Event>(); protected cvaDisabled = false; private onModelChange: (value: number) => void = () => {}; protected onModelTouched: () => void = () => {}; readonly circumference = 2 * Math.PI * 40; readonly dashOffset = computed(() => { const range = Math.max(1, this.max() - this.min()); const fraction = Math.max(0, Math.min(1, (this.value() - this.min()) / range)); return this.circumference * (1 - fraction); });
  writeValue(value: number | null): void { this.value.set(this.normalizeValue(value == null ? this.min() : Number(value))); } registerOnChange(fn: (value: number) => void): void { this.onModelChange = fn; } registerOnTouched(fn: () => void): void { this.onModelTouched = fn; } setDisabledState(disabled: boolean): void { this.cvaDisabled = disabled; }
  private normalizeValue(value: number): number { const min = this.min(); const max = Math.max(min, this.max()); const step = Math.max(Number.EPSILON, this.step()); const snapped = min + Math.round((value - min) / step) * step; return Math.max(min, Math.min(max, Number(snapped.toFixed(10)))); }
  onInput(event: Event): void { if (this.disabled() || this.readonly() || this.cvaDisabled) return; const next = this.normalizeValue(Number((event.target as HTMLInputElement).value)); this.value.set(next); this.onModelChange(next); this.valueChangeEvent.emit(next); this.onChange.emit(next); }
}
