import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, model, output } from '@angular/core';
import { P2_SHARED_STYLES } from './p2-shared';

export interface OrganizationNode { key: string; label: string; subtitle?: string; image?: string; children?: OrganizationNode[]; disabled?: boolean; }
interface FlatOrganizationNode { node: OrganizationNode; level: number; last: boolean; }

@Component({
  selector: 'orc-organization-chart', standalone: true,
  template: `<section class="orc-org" [attr.aria-label]="label()"><div class="tree">@for (item of flatNodes(); track item.node.key) { <article class="node" [class.disabled]="item.node.disabled" [style.margin-left.rem]="item.level * 2.2"><div class="card" (click)="select(item.node)">@if (item.node.image) { <img [src]="item.node.image" [alt]="item.node.label" /> }<strong>{{ item.node.label }}</strong>@if (item.node.subtitle) { <small>{{ item.node.subtitle }}</small> }</div></article> }</div></section>`,
  styles: [P2_SHARED_STYLES + `.orc-org{width:100%;overflow:auto}.tree{min-width:18rem;padding:1rem}.node{position:relative;padding:.35rem 0}.node:before{content:'';position:absolute;top:-.35rem;left:-1.1rem;width:1px;height:calc(100% + .35rem);background:#cbd5e1}.node:first-child:before{top:50%;height:50%}.card{display:grid;gap:.15rem;width:max-content;min-width:10rem;padding:.65rem .8rem;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;box-shadow:0 2px 6px #0f172a0d;cursor:pointer}.card:hover{border-color:#2563eb;background:#eff6ff}.card img{width:2rem;height:2rem;border-radius:50%;object-fit:cover}.card small{color:#64748b}.node.disabled{opacity:.5}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OrganizationChartComponent { readonly value = input<OrganizationNode[]>([]); readonly label = input('Organization chart'); readonly selected = model<string | null>(null); readonly nodeSelect = output<OrganizationNode>(); readonly flatNodes = computed<FlatOrganizationNode[]>(() => { const result: FlatOrganizationNode[] = []; const visit = (nodes: OrganizationNode[], level: number): void => { nodes.forEach((node, index) => { result.push({ node, level, last: index === nodes.length - 1 }); if (node.children?.length) visit(node.children, level + 1); }); }; visit(this.value(), 0); return result; }); select(node: OrganizationNode): void { if (node.disabled) return; this.selected.set(node.key); this.nodeSelect.emit(node); } }

@Component({
  selector: 'orc-knob', standalone: true,
  template: `<div class="orc-knob" [attr.aria-label]="ariaLabel()"><svg viewBox="0 0 100 100" role="img"><circle class="track" cx="50" cy="50" r="40" /><circle class="progress" cx="50" cy="50" r="40" [style.stroke-dasharray]="circumference" [style.stroke-dashoffset]="dashOffset()" /><text x="50" y="54" text-anchor="middle">{{ value() }}{{ suffix() }}</text></svg><input type="range" [min]="min()" [max]="max()" [step]="step()" [value]="value()" [disabled]="disabled()" (input)="onInput($event)" [attr.aria-label]="ariaLabel()" /></div>`,
  styles: [P2_SHARED_STYLES + `.orc-knob{position:relative;display:inline-block;width:8rem;height:8rem}.orc-knob svg{width:100%;height:100%;transform:rotate(-90deg)}.orc-knob circle{fill:none;stroke-width:10}.orc-knob .track{stroke:#e2e8f0}.orc-knob .progress{stroke:#2563eb;stroke-linecap:round;transition:stroke-dashoffset .15s}.orc-knob text{fill:#0f172a;font-size:1rem;font-weight:700;transform:rotate(90deg);transform-origin:50px 50px}.orc-knob input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:pointer}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KnobComponent { readonly value = model(0); readonly min = input(0); readonly max = input(100); readonly step = input(1); readonly suffix = input(''); readonly disabled = input(false, { transform: booleanAttribute }); readonly ariaLabel = input('Knob'); readonly valueChangeEvent = output<number>(); readonly circumference = 2 * Math.PI * 40; readonly dashOffset = computed(() => { const range = Math.max(1, this.max() - this.min()); const fraction = Math.max(0, Math.min(1, (this.value() - this.min()) / range)); return this.circumference * (1 - fraction); }); onInput(event: Event): void { const next = Number((event.target as HTMLInputElement).value); this.value.set(next); this.valueChangeEvent.emit(next); } }
